=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

module TampaEventsAPI
  VERSION = '1.0.0'
end
