baseURL = 'https://tampa.dev/'
languageCode = 'en-us'
title = "Tampa Bay's Tech Meetups & Developer Communities"
theme = "newsroom"
author = "Tampa Devs"
canonifyurls = true
paginate = 6000

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2


# ids used below are not valid. Replace with valid ones
[params]
  # locale = "en_US"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # mainSections = ["blog", "docs"] see https://gohugo.io/functions/where/#mainsections
  # uncomment the line below will disable darkmode by default.
  # uncomment and set value below to either "light" or "dark" to make default mode dark.
  # defaultMode = "" # Note that the UI control for toggling darkmode will remain in place. This way, the user can decide which mode they would like to use while browsing your website
  faviconsDir = "images/icons/" # with a trailing slash
  blogDir = "post" # edit
  disableDarkMode = true
  keywords = "tampa meetup groups, tampa developer groups, tampa developer communities, tampa developer meetup, tampa developer events, tampa technology conference, tampa tech meetup, tampa tech meetup groups, tampa data science and ai groups"
  description = "Tampa Bay's Best Technology & Developer Communities, Meetup Groups, Conferences, and Events"
  image = "https://tampa.dev/images/tampadevs2.jpg"
  author = "Tampa Devs"
  logo = "https://www.tampadevs.com"