/*
Tampa.dev Platform API

Testing FollowsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tampaevents

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/TampaDevs/tampa.dev/clients/go"
)

func Test_tampaevents_FollowsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FollowsAPIService V1UsersUsernameFollowDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		httpRes, err := apiClient.FollowsAPI.V1UsersUsernameFollowDelete(context.Background(), username).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FollowsAPIService V1UsersUsernameFollowPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		resp, httpRes, err := apiClient.FollowsAPI.V1UsersUsernameFollowPost(context.Background(), username).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FollowsAPIService V1UsersUsernameFollowersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		resp, httpRes, err := apiClient.FollowsAPI.V1UsersUsernameFollowersGet(context.Background(), username).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FollowsAPIService V1UsersUsernameFollowingGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		resp, httpRes, err := apiClient.FollowsAPI.V1UsersUsernameFollowingGet(context.Background(), username).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
