/*
Tampa Events API

Community events aggregation API for Tampa Bay tech meetups and events

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// EventsAPIService EventsAPI service
type EventsAPIService service

type ApiCall20260125EventsGetRequest struct {
	ctx context.Context
	ApiService *EventsAPIService
	groups *string
	noonline *string
	withinHours *string
	withinDays *string
	noempty *string
}

func (r ApiCall20260125EventsGetRequest) Groups(groups string) ApiCall20260125EventsGetRequest {
	r.groups = &groups
	return r
}

func (r ApiCall20260125EventsGetRequest) Noonline(noonline string) ApiCall20260125EventsGetRequest {
	r.noonline = &noonline
	return r
}

func (r ApiCall20260125EventsGetRequest) WithinHours(withinHours string) ApiCall20260125EventsGetRequest {
	r.withinHours = &withinHours
	return r
}

func (r ApiCall20260125EventsGetRequest) WithinDays(withinDays string) ApiCall20260125EventsGetRequest {
	r.withinDays = &withinDays
	return r
}

func (r ApiCall20260125EventsGetRequest) Noempty(noempty string) ApiCall20260125EventsGetRequest {
	r.noempty = &noempty
	return r
}

func (r ApiCall20260125EventsGetRequest) Execute() ([]ApiApi20260125EventsGet200ResponseInner, *http.Response, error) {
	return r.ApiService.Call20260125EventsGetExecute(r)
}

/*
Call20260125EventsGet Get all events

Returns a list of all upcoming events, optionally filtered by query parameters

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCall20260125EventsGetRequest
*/
func (a *EventsAPIService) Call20260125EventsGet(ctx context.Context) ApiCall20260125EventsGetRequest {
	return ApiCall20260125EventsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []ApiApi20260125EventsGet200ResponseInner
func (a *EventsAPIService) Call20260125EventsGetExecute(r ApiCall20260125EventsGetRequest) ([]ApiApi20260125EventsGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ApiApi20260125EventsGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EventsAPIService.Call20260125EventsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/2026-01-25/events"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.groups != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "groups", r.groups, "form", "")
	}
	if r.noonline != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "noonline", r.noonline, "form", "")
	}
	if r.withinHours != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "within_hours", r.withinHours, "form", "")
	}
	if r.withinDays != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "within_days", r.withinDays, "form", "")
	}
	if r.noempty != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "noempty", r.noempty, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "text/plain"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCall20260125EventsNextGetRequest struct {
	ctx context.Context
	ApiService *EventsAPIService
	groups *string
	noonline *string
	withinHours *string
	withinDays *string
	noempty *string
}

func (r ApiCall20260125EventsNextGetRequest) Groups(groups string) ApiCall20260125EventsNextGetRequest {
	r.groups = &groups
	return r
}

func (r ApiCall20260125EventsNextGetRequest) Noonline(noonline string) ApiCall20260125EventsNextGetRequest {
	r.noonline = &noonline
	return r
}

func (r ApiCall20260125EventsNextGetRequest) WithinHours(withinHours string) ApiCall20260125EventsNextGetRequest {
	r.withinHours = &withinHours
	return r
}

func (r ApiCall20260125EventsNextGetRequest) WithinDays(withinDays string) ApiCall20260125EventsNextGetRequest {
	r.withinDays = &withinDays
	return r
}

func (r ApiCall20260125EventsNextGetRequest) Noempty(noempty string) ApiCall20260125EventsNextGetRequest {
	r.noempty = &noempty
	return r
}

func (r ApiCall20260125EventsNextGetRequest) Execute() ([]ApiApi20260125EventsGet200ResponseInner, *http.Response, error) {
	return r.ApiService.Call20260125EventsNextGetExecute(r)
}

/*
Call20260125EventsNextGet Get next event per group

Returns one upcoming event for each group (the next event)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCall20260125EventsNextGetRequest
*/
func (a *EventsAPIService) Call20260125EventsNextGet(ctx context.Context) ApiCall20260125EventsNextGetRequest {
	return ApiCall20260125EventsNextGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []ApiApi20260125EventsGet200ResponseInner
func (a *EventsAPIService) Call20260125EventsNextGetExecute(r ApiCall20260125EventsNextGetRequest) ([]ApiApi20260125EventsGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ApiApi20260125EventsGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EventsAPIService.Call20260125EventsNextGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/2026-01-25/events/next"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.groups != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "groups", r.groups, "form", "")
	}
	if r.noonline != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "noonline", r.noonline, "form", "")
	}
	if r.withinHours != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "within_hours", r.withinHours, "form", "")
	}
	if r.withinDays != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "within_days", r.withinDays, "form", "")
	}
	if r.noempty != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "noempty", r.noempty, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "text/plain"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
