/*
Tampa Events API

Community events aggregation API for Tampa Bay tech meetups and events

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Api20260125SchemasGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Api20260125SchemasGet200Response{}

// Api20260125SchemasGet200Response struct for Api20260125SchemasGet200Response
type Api20260125SchemasGet200Response struct {
	Schemas []ApiApi20260125SchemasGet200ResponseSchemasInner `json:"schemas"`
	Version string `json:"version"`
}

type _Api20260125SchemasGet200Response Api20260125SchemasGet200Response

// NewApi20260125SchemasGet200Response instantiates a new Api20260125SchemasGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApi20260125SchemasGet200Response(schemas []ApiApi20260125SchemasGet200ResponseSchemasInner, version string) *Api20260125SchemasGet200Response {
	this := Api20260125SchemasGet200Response{}
	this.Schemas = schemas
	this.Version = version
	return &this
}

// NewApi20260125SchemasGet200ResponseWithDefaults instantiates a new Api20260125SchemasGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApi20260125SchemasGet200ResponseWithDefaults() *Api20260125SchemasGet200Response {
	this := Api20260125SchemasGet200Response{}
	return &this
}

// GetSchemas returns the Schemas field value
func (o *Api20260125SchemasGet200Response) GetSchemas() []ApiApi20260125SchemasGet200ResponseSchemasInner {
	if o == nil {
		var ret []ApiApi20260125SchemasGet200ResponseSchemasInner
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *Api20260125SchemasGet200Response) GetSchemasOk() ([]ApiApi20260125SchemasGet200ResponseSchemasInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *Api20260125SchemasGet200Response) SetSchemas(v []ApiApi20260125SchemasGet200ResponseSchemasInner) {
	o.Schemas = v
}

// GetVersion returns the Version field value
func (o *Api20260125SchemasGet200Response) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Api20260125SchemasGet200Response) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Api20260125SchemasGet200Response) SetVersion(v string) {
	o.Version = v
}

func (o Api20260125SchemasGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Api20260125SchemasGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *Api20260125SchemasGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemas",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApi20260125SchemasGet200Response := _Api20260125SchemasGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApi20260125SchemasGet200Response)

	if err != nil {
		return err
	}

	*o = Api20260125SchemasGet200Response(varApi20260125SchemasGet200Response)

	return err
}

type NullableApi20260125SchemasGet200Response struct {
	value *Api20260125SchemasGet200Response
	isSet bool
}

func (v NullableApi20260125SchemasGet200Response) Get() *Api20260125SchemasGet200Response {
	return v.value
}

func (v *NullableApi20260125SchemasGet200Response) Set(val *Api20260125SchemasGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApi20260125SchemasGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApi20260125SchemasGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApi20260125SchemasGet200Response(val *Api20260125SchemasGet200Response) *NullableApi20260125SchemasGet200Response {
	return &NullableApi20260125SchemasGet200Response{value: val, isSet: true}
}

func (v NullableApi20260125SchemasGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApi20260125SchemasGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


