/*
Tampa Events API

Community events aggregation API for Tampa Bay tech meetups and events

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Api20260125SchemasNameGet404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Api20260125SchemasNameGet404Response{}

// Api20260125SchemasNameGet404Response struct for Api20260125SchemasNameGet404Response
type Api20260125SchemasNameGet404Response struct {
	Error string `json:"error"`
	Available []string `json:"available"`
}

type _Api20260125SchemasNameGet404Response Api20260125SchemasNameGet404Response

// NewApi20260125SchemasNameGet404Response instantiates a new Api20260125SchemasNameGet404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApi20260125SchemasNameGet404Response(error_ string, available []string) *Api20260125SchemasNameGet404Response {
	this := Api20260125SchemasNameGet404Response{}
	this.Error = error_
	this.Available = available
	return &this
}

// NewApi20260125SchemasNameGet404ResponseWithDefaults instantiates a new Api20260125SchemasNameGet404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApi20260125SchemasNameGet404ResponseWithDefaults() *Api20260125SchemasNameGet404Response {
	this := Api20260125SchemasNameGet404Response{}
	return &this
}

// GetError returns the Error field value
func (o *Api20260125SchemasNameGet404Response) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *Api20260125SchemasNameGet404Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *Api20260125SchemasNameGet404Response) SetError(v string) {
	o.Error = v
}

// GetAvailable returns the Available field value
func (o *Api20260125SchemasNameGet404Response) GetAvailable() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *Api20260125SchemasNameGet404Response) GetAvailableOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Available, true
}

// SetAvailable sets field value
func (o *Api20260125SchemasNameGet404Response) SetAvailable(v []string) {
	o.Available = v
}

func (o Api20260125SchemasNameGet404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Api20260125SchemasNameGet404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["available"] = o.Available
	return toSerialize, nil
}

func (o *Api20260125SchemasNameGet404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"available",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApi20260125SchemasNameGet404Response := _Api20260125SchemasNameGet404Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApi20260125SchemasNameGet404Response)

	if err != nil {
		return err
	}

	*o = Api20260125SchemasNameGet404Response(varApi20260125SchemasNameGet404Response)

	return err
}

type NullableApi20260125SchemasNameGet404Response struct {
	value *Api20260125SchemasNameGet404Response
	isSet bool
}

func (v NullableApi20260125SchemasNameGet404Response) Get() *Api20260125SchemasNameGet404Response {
	return v.value
}

func (v *NullableApi20260125SchemasNameGet404Response) Set(val *Api20260125SchemasNameGet404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApi20260125SchemasNameGet404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApi20260125SchemasNameGet404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApi20260125SchemasNameGet404Response(val *Api20260125SchemasNameGet404Response) *NullableApi20260125SchemasNameGet404Response {
	return &NullableApi20260125SchemasNameGet404Response{value: val, isSet: true}
}

func (v NullableApi20260125SchemasNameGet404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApi20260125SchemasNameGet404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


