/*
Tampa Events API

Community events aggregation API for Tampa Bay tech meetups and events

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceStatusGet200ResponsePlatformsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceStatusGet200ResponsePlatformsInner{}

// ServiceStatusGet200ResponsePlatformsInner struct for ServiceStatusGet200ResponsePlatformsInner
type ServiceStatusGet200ResponsePlatformsInner struct {
	Name string `json:"name"`
	Configured bool `json:"configured"`
}

type _ServiceStatusGet200ResponsePlatformsInner ServiceStatusGet200ResponsePlatformsInner

// NewServiceStatusGet200ResponsePlatformsInner instantiates a new ServiceStatusGet200ResponsePlatformsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceStatusGet200ResponsePlatformsInner(name string, configured bool) *ServiceStatusGet200ResponsePlatformsInner {
	this := ServiceStatusGet200ResponsePlatformsInner{}
	this.Name = name
	this.Configured = configured
	return &this
}

// NewServiceStatusGet200ResponsePlatformsInnerWithDefaults instantiates a new ServiceStatusGet200ResponsePlatformsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceStatusGet200ResponsePlatformsInnerWithDefaults() *ServiceStatusGet200ResponsePlatformsInner {
	this := ServiceStatusGet200ResponsePlatformsInner{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceStatusGet200ResponsePlatformsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceStatusGet200ResponsePlatformsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceStatusGet200ResponsePlatformsInner) SetName(v string) {
	o.Name = v
}

// GetConfigured returns the Configured field value
func (o *ServiceStatusGet200ResponsePlatformsInner) GetConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value
// and a boolean to check if the value has been set.
func (o *ServiceStatusGet200ResponsePlatformsInner) GetConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configured, true
}

// SetConfigured sets field value
func (o *ServiceStatusGet200ResponsePlatformsInner) SetConfigured(v bool) {
	o.Configured = v
}

func (o ServiceStatusGet200ResponsePlatformsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceStatusGet200ResponsePlatformsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["configured"] = o.Configured
	return toSerialize, nil
}

func (o *ServiceStatusGet200ResponsePlatformsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"configured",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceStatusGet200ResponsePlatformsInner := _ServiceStatusGet200ResponsePlatformsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceStatusGet200ResponsePlatformsInner)

	if err != nil {
		return err
	}

	*o = ServiceStatusGet200ResponsePlatformsInner(varServiceStatusGet200ResponsePlatformsInner)

	return err
}

type NullableServiceStatusGet200ResponsePlatformsInner struct {
	value *ServiceStatusGet200ResponsePlatformsInner
	isSet bool
}

func (v NullableServiceStatusGet200ResponsePlatformsInner) Get() *ServiceStatusGet200ResponsePlatformsInner {
	return v.value
}

func (v *NullableServiceStatusGet200ResponsePlatformsInner) Set(val *ServiceStatusGet200ResponsePlatformsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceStatusGet200ResponsePlatformsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceStatusGet200ResponsePlatformsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceStatusGet200ResponsePlatformsInner(val *ServiceStatusGet200ResponsePlatformsInner) *NullableServiceStatusGet200ResponsePlatformsInner {
	return &NullableServiceStatusGet200ResponsePlatformsInner{value: val, isSet: true}
}

func (v NullableServiceStatusGet200ResponsePlatformsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceStatusGet200ResponsePlatformsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


