/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VPagination{}

// VPagination struct for VPagination
type VPagination struct {
	// Total number of items (may be absent if count is expensive)
	Total *float32 `json:"total,omitempty"`
	// Maximum items per page
	Limit float32 `json:"limit"`
	// Number of items skipped
	Offset float32 `json:"offset"`
	// Whether more items exist beyond this page
	HasMore bool `json:"hasMore"`
}

type _VPagination VPagination

// NewVPagination instantiates a new VPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVPagination(limit float32, offset float32, hasMore bool) *VPagination {
	this := VPagination{}
	this.Limit = limit
	this.Offset = offset
	this.HasMore = hasMore
	return &this
}

// NewVPaginationWithDefaults instantiates a new VPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVPaginationWithDefaults() *VPagination {
	this := VPagination{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VPagination) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPagination) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VPagination) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *VPagination) SetTotal(v float32) {
	o.Total = &v
}

// GetLimit returns the Limit field value
func (o *VPagination) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *VPagination) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *VPagination) SetLimit(v float32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *VPagination) GetOffset() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *VPagination) GetOffsetOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *VPagination) SetOffset(v float32) {
	o.Offset = v
}

// GetHasMore returns the HasMore field value
func (o *VPagination) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *VPagination) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *VPagination) SetHasMore(v bool) {
	o.HasMore = v
}

func (o VPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VPagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	toSerialize["hasMore"] = o.HasMore
	return toSerialize, nil
}

func (o *VPagination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limit",
		"offset",
		"hasMore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVPagination := _VPagination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVPagination)

	if err != nil {
		return err
	}

	*o = VPagination(varVPagination)

	return err
}

type NullableVPagination struct {
	value *VPagination
	isSet bool
}

func (v NullableVPagination) Get() *VPagination {
	return v.value
}

func (v *NullableVPagination) Set(val *VPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableVPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableVPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVPagination(val *VPagination) *NullableVPagination {
	return &NullableVPagination{value: val, isSet: true}
}

func (v NullableVPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


