/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VClaimBadgeResponseBadge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VClaimBadgeResponseBadge{}

// VClaimBadgeResponseBadge struct for VClaimBadgeResponseBadge
type VClaimBadgeResponseBadge struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type _VClaimBadgeResponseBadge VClaimBadgeResponseBadge

// NewVClaimBadgeResponseBadge instantiates a new VClaimBadgeResponseBadge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVClaimBadgeResponseBadge(name string, slug string) *VClaimBadgeResponseBadge {
	this := VClaimBadgeResponseBadge{}
	this.Name = name
	this.Slug = slug
	return &this
}

// NewVClaimBadgeResponseBadgeWithDefaults instantiates a new VClaimBadgeResponseBadge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVClaimBadgeResponseBadgeWithDefaults() *VClaimBadgeResponseBadge {
	this := VClaimBadgeResponseBadge{}
	return &this
}

// GetName returns the Name field value
func (o *VClaimBadgeResponseBadge) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VClaimBadgeResponseBadge) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VClaimBadgeResponseBadge) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *VClaimBadgeResponseBadge) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *VClaimBadgeResponseBadge) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *VClaimBadgeResponseBadge) SetSlug(v string) {
	o.Slug = v
}

func (o VClaimBadgeResponseBadge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VClaimBadgeResponseBadge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	return toSerialize, nil
}

func (o *VClaimBadgeResponseBadge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVClaimBadgeResponseBadge := _VClaimBadgeResponseBadge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVClaimBadgeResponseBadge)

	if err != nil {
		return err
	}

	*o = VClaimBadgeResponseBadge(varVClaimBadgeResponseBadge)

	return err
}

type NullableVClaimBadgeResponseBadge struct {
	value *VClaimBadgeResponseBadge
	isSet bool
}

func (v NullableVClaimBadgeResponseBadge) Get() *VClaimBadgeResponseBadge {
	return v.value
}

func (v *NullableVClaimBadgeResponseBadge) Set(val *VClaimBadgeResponseBadge) {
	v.value = val
	v.isSet = true
}

func (v NullableVClaimBadgeResponseBadge) IsSet() bool {
	return v.isSet
}

func (v *NullableVClaimBadgeResponseBadge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVClaimBadgeResponseBadge(val *VClaimBadgeResponseBadge) *NullableVClaimBadgeResponseBadge {
	return &NullableVClaimBadgeResponseBadge{value: val, isSet: true}
}

func (v NullableVClaimBadgeResponseBadge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVClaimBadgeResponseBadge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


