/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VGroupDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VGroupDetail{}

// VGroupDetail struct for VGroupDetail
type VGroupDetail struct {
	Id string `json:"id"`
	Urlname string `json:"urlname"`
	Name string `json:"name"`
	Description string `json:"description"`
	Link string `json:"link"`
	Website string `json:"website"`
	MemberCount float32 `json:"memberCount"`
	PhotoUrl string `json:"photoUrl"`
	Tags interface{} `json:"tags,omitempty"`
	SocialLinks interface{} `json:"socialLinks,omitempty"`
	UpcomingEvents []VVGroupDetailAllOfUpcomingEvents `json:"upcomingEvents"`
}

type _VGroupDetail VGroupDetail

// NewVGroupDetail instantiates a new VGroupDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVGroupDetail(id string, urlname string, name string, description string, link string, website string, memberCount float32, photoUrl string, upcomingEvents []VVGroupDetailAllOfUpcomingEvents) *VGroupDetail {
	this := VGroupDetail{}
	this.Id = id
	this.Urlname = urlname
	this.Name = name
	this.Description = description
	this.Link = link
	this.Website = website
	this.MemberCount = memberCount
	this.PhotoUrl = photoUrl
	this.UpcomingEvents = upcomingEvents
	return &this
}

// NewVGroupDetailWithDefaults instantiates a new VGroupDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVGroupDetailWithDefaults() *VGroupDetail {
	this := VGroupDetail{}
	return &this
}

// GetId returns the Id field value
func (o *VGroupDetail) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VGroupDetail) SetId(v string) {
	o.Id = v
}

// GetUrlname returns the Urlname field value
func (o *VGroupDetail) GetUrlname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Urlname
}

// GetUrlnameOk returns a tuple with the Urlname field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetUrlnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Urlname, true
}

// SetUrlname sets field value
func (o *VGroupDetail) SetUrlname(v string) {
	o.Urlname = v
}

// GetName returns the Name field value
func (o *VGroupDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VGroupDetail) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *VGroupDetail) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *VGroupDetail) SetDescription(v string) {
	o.Description = v
}

// GetLink returns the Link field value
func (o *VGroupDetail) GetLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *VGroupDetail) SetLink(v string) {
	o.Link = v
}

// GetWebsite returns the Website field value
func (o *VGroupDetail) GetWebsite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Website
}

// GetWebsiteOk returns a tuple with the Website field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetWebsiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Website, true
}

// SetWebsite sets field value
func (o *VGroupDetail) SetWebsite(v string) {
	o.Website = v
}

// GetMemberCount returns the MemberCount field value
func (o *VGroupDetail) GetMemberCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetMemberCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberCount, true
}

// SetMemberCount sets field value
func (o *VGroupDetail) SetMemberCount(v float32) {
	o.MemberCount = v
}

// GetPhotoUrl returns the PhotoUrl field value
func (o *VGroupDetail) GetPhotoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhotoUrl
}

// GetPhotoUrlOk returns a tuple with the PhotoUrl field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetPhotoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhotoUrl, true
}

// SetPhotoUrl sets field value
func (o *VGroupDetail) SetPhotoUrl(v string) {
	o.PhotoUrl = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VGroupDetail) GetTags() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VGroupDetail) GetTagsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return &o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *VGroupDetail) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given interface{} and assigns it to the Tags field.
func (o *VGroupDetail) SetTags(v interface{}) {
	o.Tags = v
}

// GetSocialLinks returns the SocialLinks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VGroupDetail) GetSocialLinks() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SocialLinks
}

// GetSocialLinksOk returns a tuple with the SocialLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VGroupDetail) GetSocialLinksOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SocialLinks) {
		return nil, false
	}
	return &o.SocialLinks, true
}

// HasSocialLinks returns a boolean if a field has been set.
func (o *VGroupDetail) HasSocialLinks() bool {
	if o != nil && !IsNil(o.SocialLinks) {
		return true
	}

	return false
}

// SetSocialLinks gets a reference to the given interface{} and assigns it to the SocialLinks field.
func (o *VGroupDetail) SetSocialLinks(v interface{}) {
	o.SocialLinks = v
}

// GetUpcomingEvents returns the UpcomingEvents field value
func (o *VGroupDetail) GetUpcomingEvents() []VVGroupDetailAllOfUpcomingEvents {
	if o == nil {
		var ret []VVGroupDetailAllOfUpcomingEvents
		return ret
	}

	return o.UpcomingEvents
}

// GetUpcomingEventsOk returns a tuple with the UpcomingEvents field value
// and a boolean to check if the value has been set.
func (o *VGroupDetail) GetUpcomingEventsOk() ([]VVGroupDetailAllOfUpcomingEvents, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpcomingEvents, true
}

// SetUpcomingEvents sets field value
func (o *VGroupDetail) SetUpcomingEvents(v []VVGroupDetailAllOfUpcomingEvents) {
	o.UpcomingEvents = v
}

func (o VGroupDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VGroupDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["urlname"] = o.Urlname
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["link"] = o.Link
	toSerialize["website"] = o.Website
	toSerialize["memberCount"] = o.MemberCount
	toSerialize["photoUrl"] = o.PhotoUrl
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.SocialLinks != nil {
		toSerialize["socialLinks"] = o.SocialLinks
	}
	toSerialize["upcomingEvents"] = o.UpcomingEvents
	return toSerialize, nil
}

func (o *VGroupDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"urlname",
		"name",
		"description",
		"link",
		"website",
		"memberCount",
		"photoUrl",
		"upcomingEvents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVGroupDetail := _VGroupDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVGroupDetail)

	if err != nil {
		return err
	}

	*o = VGroupDetail(varVGroupDetail)

	return err
}

type NullableVGroupDetail struct {
	value *VGroupDetail
	isSet bool
}

func (v NullableVGroupDetail) Get() *VGroupDetail {
	return v.value
}

func (v *NullableVGroupDetail) Set(val *VGroupDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableVGroupDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableVGroupDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVGroupDetail(val *VGroupDetail) *NullableVGroupDetail {
	return &NullableVGroupDetail{value: val, isSet: true}
}

func (v NullableVGroupDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVGroupDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


