/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VUserEntitlement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VUserEntitlement{}

// VUserEntitlement struct for VUserEntitlement
type VUserEntitlement struct {
	Id string `json:"id"`
	// Entitlement key (e.g., dev.tampa.group.create)
	Entitlement string `json:"entitlement"`
	// ISO timestamp when entitlement was granted
	GrantedAt string `json:"grantedAt"`
	// ISO timestamp when entitlement expires, or null if permanent
	ExpiresAt string `json:"expiresAt"`
	// How the entitlement was granted (e.g., admin, achievement)
	Source string `json:"source"`
}

type _VUserEntitlement VUserEntitlement

// NewVUserEntitlement instantiates a new VUserEntitlement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVUserEntitlement(id string, entitlement string, grantedAt string, expiresAt string, source string) *VUserEntitlement {
	this := VUserEntitlement{}
	this.Id = id
	this.Entitlement = entitlement
	this.GrantedAt = grantedAt
	this.ExpiresAt = expiresAt
	this.Source = source
	return &this
}

// NewVUserEntitlementWithDefaults instantiates a new VUserEntitlement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVUserEntitlementWithDefaults() *VUserEntitlement {
	this := VUserEntitlement{}
	return &this
}

// GetId returns the Id field value
func (o *VUserEntitlement) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VUserEntitlement) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VUserEntitlement) SetId(v string) {
	o.Id = v
}

// GetEntitlement returns the Entitlement field value
func (o *VUserEntitlement) GetEntitlement() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entitlement
}

// GetEntitlementOk returns a tuple with the Entitlement field value
// and a boolean to check if the value has been set.
func (o *VUserEntitlement) GetEntitlementOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entitlement, true
}

// SetEntitlement sets field value
func (o *VUserEntitlement) SetEntitlement(v string) {
	o.Entitlement = v
}

// GetGrantedAt returns the GrantedAt field value
func (o *VUserEntitlement) GetGrantedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantedAt
}

// GetGrantedAtOk returns a tuple with the GrantedAt field value
// and a boolean to check if the value has been set.
func (o *VUserEntitlement) GetGrantedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantedAt, true
}

// SetGrantedAt sets field value
func (o *VUserEntitlement) SetGrantedAt(v string) {
	o.GrantedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *VUserEntitlement) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *VUserEntitlement) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *VUserEntitlement) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetSource returns the Source field value
func (o *VUserEntitlement) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *VUserEntitlement) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *VUserEntitlement) SetSource(v string) {
	o.Source = v
}

func (o VUserEntitlement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VUserEntitlement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["entitlement"] = o.Entitlement
	toSerialize["grantedAt"] = o.GrantedAt
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *VUserEntitlement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"entitlement",
		"grantedAt",
		"expiresAt",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVUserEntitlement := _VUserEntitlement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVUserEntitlement)

	if err != nil {
		return err
	}

	*o = VUserEntitlement(varVUserEntitlement)

	return err
}

type NullableVUserEntitlement struct {
	value *VUserEntitlement
	isSet bool
}

func (v NullableVUserEntitlement) Get() *VUserEntitlement {
	return v.value
}

func (v *NullableVUserEntitlement) Set(val *VUserEntitlement) {
	v.value = val
	v.isSet = true
}

func (v NullableVUserEntitlement) IsSet() bool {
	return v.isSet
}

func (v *NullableVUserEntitlement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVUserEntitlement(val *VUserEntitlement) *NullableVUserEntitlement {
	return &NullableVUserEntitlement{value: val, isSet: true}
}

func (v NullableVUserEntitlement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVUserEntitlement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


