/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1EventsEventIdRsvpGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1EventsEventIdRsvpGet200Response{}

// VV1EventsEventIdRsvpGet200Response struct for VV1EventsEventIdRsvpGet200Response
type VV1EventsEventIdRsvpGet200Response struct {
	Data VVRsvpStatusResponse `json:"data"`
}

type _VV1EventsEventIdRsvpGet200Response VV1EventsEventIdRsvpGet200Response

// NewVV1EventsEventIdRsvpGet200Response instantiates a new VV1EventsEventIdRsvpGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1EventsEventIdRsvpGet200Response(data VVRsvpStatusResponse) *VV1EventsEventIdRsvpGet200Response {
	this := VV1EventsEventIdRsvpGet200Response{}
	this.Data = data
	return &this
}

// NewVV1EventsEventIdRsvpGet200ResponseWithDefaults instantiates a new VV1EventsEventIdRsvpGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1EventsEventIdRsvpGet200ResponseWithDefaults() *VV1EventsEventIdRsvpGet200Response {
	this := VV1EventsEventIdRsvpGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1EventsEventIdRsvpGet200Response) GetData() VVRsvpStatusResponse {
	if o == nil {
		var ret VVRsvpStatusResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1EventsEventIdRsvpGet200Response) GetDataOk() (*VVRsvpStatusResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VV1EventsEventIdRsvpGet200Response) SetData(v VVRsvpStatusResponse) {
	o.Data = v
}

func (o VV1EventsEventIdRsvpGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1EventsEventIdRsvpGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VV1EventsEventIdRsvpGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1EventsEventIdRsvpGet200Response := _VV1EventsEventIdRsvpGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1EventsEventIdRsvpGet200Response)

	if err != nil {
		return err
	}

	*o = VV1EventsEventIdRsvpGet200Response(varVV1EventsEventIdRsvpGet200Response)

	return err
}

type NullableVV1EventsEventIdRsvpGet200Response struct {
	value *VV1EventsEventIdRsvpGet200Response
	isSet bool
}

func (v NullableVV1EventsEventIdRsvpGet200Response) Get() *VV1EventsEventIdRsvpGet200Response {
	return v.value
}

func (v *NullableVV1EventsEventIdRsvpGet200Response) Set(val *VV1EventsEventIdRsvpGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1EventsEventIdRsvpGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1EventsEventIdRsvpGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1EventsEventIdRsvpGet200Response(val *VV1EventsEventIdRsvpGet200Response) *NullableVV1EventsEventIdRsvpGet200Response {
	return &NullableVV1EventsEventIdRsvpGet200Response{value: val, isSet: true}
}

func (v NullableVV1EventsEventIdRsvpGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1EventsEventIdRsvpGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


