/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1ProfileTokensGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1ProfileTokensGet200Response{}

// VV1ProfileTokensGet200Response struct for VV1ProfileTokensGet200Response
type VV1ProfileTokensGet200Response struct {
	Data []VVToken `json:"data"`
}

type _VV1ProfileTokensGet200Response VV1ProfileTokensGet200Response

// NewVV1ProfileTokensGet200Response instantiates a new VV1ProfileTokensGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1ProfileTokensGet200Response(data []VVToken) *VV1ProfileTokensGet200Response {
	this := VV1ProfileTokensGet200Response{}
	this.Data = data
	return &this
}

// NewVV1ProfileTokensGet200ResponseWithDefaults instantiates a new VV1ProfileTokensGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1ProfileTokensGet200ResponseWithDefaults() *VV1ProfileTokensGet200Response {
	this := VV1ProfileTokensGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1ProfileTokensGet200Response) GetData() []VVToken {
	if o == nil {
		var ret []VVToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1ProfileTokensGet200Response) GetDataOk() ([]VVToken, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VV1ProfileTokensGet200Response) SetData(v []VVToken) {
	o.Data = v
}

func (o VV1ProfileTokensGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1ProfileTokensGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VV1ProfileTokensGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1ProfileTokensGet200Response := _VV1ProfileTokensGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1ProfileTokensGet200Response)

	if err != nil {
		return err
	}

	*o = VV1ProfileTokensGet200Response(varVV1ProfileTokensGet200Response)

	return err
}

type NullableVV1ProfileTokensGet200Response struct {
	value *VV1ProfileTokensGet200Response
	isSet bool
}

func (v NullableVV1ProfileTokensGet200Response) Get() *VV1ProfileTokensGet200Response {
	return v.value
}

func (v *NullableVV1ProfileTokensGet200Response) Set(val *VV1ProfileTokensGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1ProfileTokensGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1ProfileTokensGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1ProfileTokensGet200Response(val *VV1ProfileTokensGet200Response) *NullableVV1ProfileTokensGet200Response {
	return &NullableVV1ProfileTokensGet200Response{value: val, isSet: true}
}

func (v NullableVV1ProfileTokensGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1ProfileTokensGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


