/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VClaimInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VClaimInfo{}

// VClaimInfo struct for VClaimInfo
type VClaimInfo struct {
	Badge VVClaimInfoBadge `json:"badge"`
	Group VVClaimInfoGroup `json:"group"`
	Claimable bool `json:"claimable"`
	Reason *string `json:"reason,omitempty"`
}

type _VClaimInfo VClaimInfo

// NewVClaimInfo instantiates a new VClaimInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVClaimInfo(badge VVClaimInfoBadge, group VVClaimInfoGroup, claimable bool) *VClaimInfo {
	this := VClaimInfo{}
	this.Badge = badge
	this.Group = group
	this.Claimable = claimable
	return &this
}

// NewVClaimInfoWithDefaults instantiates a new VClaimInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVClaimInfoWithDefaults() *VClaimInfo {
	this := VClaimInfo{}
	return &this
}

// GetBadge returns the Badge field value
func (o *VClaimInfo) GetBadge() VVClaimInfoBadge {
	if o == nil {
		var ret VVClaimInfoBadge
		return ret
	}

	return o.Badge
}

// GetBadgeOk returns a tuple with the Badge field value
// and a boolean to check if the value has been set.
func (o *VClaimInfo) GetBadgeOk() (*VVClaimInfoBadge, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Badge, true
}

// SetBadge sets field value
func (o *VClaimInfo) SetBadge(v VVClaimInfoBadge) {
	o.Badge = v
}

// GetGroup returns the Group field value
func (o *VClaimInfo) GetGroup() VVClaimInfoGroup {
	if o == nil {
		var ret VVClaimInfoGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *VClaimInfo) GetGroupOk() (*VVClaimInfoGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *VClaimInfo) SetGroup(v VVClaimInfoGroup) {
	o.Group = v
}

// GetClaimable returns the Claimable field value
func (o *VClaimInfo) GetClaimable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Claimable
}

// GetClaimableOk returns a tuple with the Claimable field value
// and a boolean to check if the value has been set.
func (o *VClaimInfo) GetClaimableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Claimable, true
}

// SetClaimable sets field value
func (o *VClaimInfo) SetClaimable(v bool) {
	o.Claimable = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *VClaimInfo) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VClaimInfo) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *VClaimInfo) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *VClaimInfo) SetReason(v string) {
	o.Reason = &v
}

func (o VClaimInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VClaimInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["badge"] = o.Badge
	toSerialize["group"] = o.Group
	toSerialize["claimable"] = o.Claimable
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *VClaimInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"badge",
		"group",
		"claimable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVClaimInfo := _VClaimInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVClaimInfo)

	if err != nil {
		return err
	}

	*o = VClaimInfo(varVClaimInfo)

	return err
}

type NullableVClaimInfo struct {
	value *VClaimInfo
	isSet bool
}

func (v NullableVClaimInfo) Get() *VClaimInfo {
	return v.value
}

func (v *NullableVClaimInfo) Set(val *VClaimInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVClaimInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVClaimInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVClaimInfo(val *VClaimInfo) *NullableVClaimInfo {
	return &NullableVClaimInfo{value: val, isSet: true}
}

func (v NullableVClaimInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVClaimInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


