/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1GroupsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1GroupsGet200Response{}

// VV1GroupsGet200Response struct for VV1GroupsGet200Response
type VV1GroupsGet200Response struct {
	Data []VVGroupListItem `json:"data"`
	Pagination VVPagination `json:"pagination"`
}

type _VV1GroupsGet200Response VV1GroupsGet200Response

// NewVV1GroupsGet200Response instantiates a new VV1GroupsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1GroupsGet200Response(data []VVGroupListItem, pagination VVPagination) *VV1GroupsGet200Response {
	this := VV1GroupsGet200Response{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewVV1GroupsGet200ResponseWithDefaults instantiates a new VV1GroupsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1GroupsGet200ResponseWithDefaults() *VV1GroupsGet200Response {
	this := VV1GroupsGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1GroupsGet200Response) GetData() []VVGroupListItem {
	if o == nil {
		var ret []VVGroupListItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1GroupsGet200Response) GetDataOk() ([]VVGroupListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VV1GroupsGet200Response) SetData(v []VVGroupListItem) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *VV1GroupsGet200Response) GetPagination() VVPagination {
	if o == nil {
		var ret VVPagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *VV1GroupsGet200Response) GetPaginationOk() (*VVPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *VV1GroupsGet200Response) SetPagination(v VVPagination) {
	o.Pagination = v
}

func (o VV1GroupsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1GroupsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *VV1GroupsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1GroupsGet200Response := _VV1GroupsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1GroupsGet200Response)

	if err != nil {
		return err
	}

	*o = VV1GroupsGet200Response(varVV1GroupsGet200Response)

	return err
}

type NullableVV1GroupsGet200Response struct {
	value *VV1GroupsGet200Response
	isSet bool
}

func (v NullableVV1GroupsGet200Response) Get() *VV1GroupsGet200Response {
	return v.value
}

func (v *NullableVV1GroupsGet200Response) Set(val *VV1GroupsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1GroupsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1GroupsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1GroupsGet200Response(val *VV1GroupsGet200Response) *NullableVV1GroupsGet200Response {
	return &NullableVV1GroupsGet200Response{value: val, isSet: true}
}

func (v NullableVV1GroupsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1GroupsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


