/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1UsersUsernameFollowPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1UsersUsernameFollowPost200ResponseData{}

// VV1UsersUsernameFollowPost200ResponseData struct for VV1UsersUsernameFollowPost200ResponseData
type VV1UsersUsernameFollowPost200ResponseData struct {
	AlreadyFollowing bool `json:"alreadyFollowing"`
}

type _VV1UsersUsernameFollowPost200ResponseData VV1UsersUsernameFollowPost200ResponseData

// NewVV1UsersUsernameFollowPost200ResponseData instantiates a new VV1UsersUsernameFollowPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1UsersUsernameFollowPost200ResponseData(alreadyFollowing bool) *VV1UsersUsernameFollowPost200ResponseData {
	this := VV1UsersUsernameFollowPost200ResponseData{}
	this.AlreadyFollowing = alreadyFollowing
	return &this
}

// NewVV1UsersUsernameFollowPost200ResponseDataWithDefaults instantiates a new VV1UsersUsernameFollowPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1UsersUsernameFollowPost200ResponseDataWithDefaults() *VV1UsersUsernameFollowPost200ResponseData {
	this := VV1UsersUsernameFollowPost200ResponseData{}
	return &this
}

// GetAlreadyFollowing returns the AlreadyFollowing field value
func (o *VV1UsersUsernameFollowPost200ResponseData) GetAlreadyFollowing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlreadyFollowing
}

// GetAlreadyFollowingOk returns a tuple with the AlreadyFollowing field value
// and a boolean to check if the value has been set.
func (o *VV1UsersUsernameFollowPost200ResponseData) GetAlreadyFollowingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlreadyFollowing, true
}

// SetAlreadyFollowing sets field value
func (o *VV1UsersUsernameFollowPost200ResponseData) SetAlreadyFollowing(v bool) {
	o.AlreadyFollowing = v
}

func (o VV1UsersUsernameFollowPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1UsersUsernameFollowPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alreadyFollowing"] = o.AlreadyFollowing
	return toSerialize, nil
}

func (o *VV1UsersUsernameFollowPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alreadyFollowing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1UsersUsernameFollowPost200ResponseData := _VV1UsersUsernameFollowPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1UsersUsernameFollowPost200ResponseData)

	if err != nil {
		return err
	}

	*o = VV1UsersUsernameFollowPost200ResponseData(varVV1UsersUsernameFollowPost200ResponseData)

	return err
}

type NullableVV1UsersUsernameFollowPost200ResponseData struct {
	value *VV1UsersUsernameFollowPost200ResponseData
	isSet bool
}

func (v NullableVV1UsersUsernameFollowPost200ResponseData) Get() *VV1UsersUsernameFollowPost200ResponseData {
	return v.value
}

func (v *NullableVV1UsersUsernameFollowPost200ResponseData) Set(val *VV1UsersUsernameFollowPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1UsersUsernameFollowPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1UsersUsernameFollowPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1UsersUsernameFollowPost200ResponseData(val *VV1UsersUsernameFollowPost200ResponseData) *NullableVV1UsersUsernameFollowPost200ResponseData {
	return &NullableVV1UsersUsernameFollowPost200ResponseData{value: val, isSet: true}
}

func (v NullableVV1UsersUsernameFollowPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1UsersUsernameFollowPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


