/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1ProfileBadgesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1ProfileBadgesGet200Response{}

// VV1ProfileBadgesGet200Response struct for VV1ProfileBadgesGet200Response
type VV1ProfileBadgesGet200Response struct {
	Data []VVUserBadge `json:"data"`
}

type _VV1ProfileBadgesGet200Response VV1ProfileBadgesGet200Response

// NewVV1ProfileBadgesGet200Response instantiates a new VV1ProfileBadgesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1ProfileBadgesGet200Response(data []VVUserBadge) *VV1ProfileBadgesGet200Response {
	this := VV1ProfileBadgesGet200Response{}
	this.Data = data
	return &this
}

// NewVV1ProfileBadgesGet200ResponseWithDefaults instantiates a new VV1ProfileBadgesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1ProfileBadgesGet200ResponseWithDefaults() *VV1ProfileBadgesGet200Response {
	this := VV1ProfileBadgesGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1ProfileBadgesGet200Response) GetData() []VVUserBadge {
	if o == nil {
		var ret []VVUserBadge
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1ProfileBadgesGet200Response) GetDataOk() ([]VVUserBadge, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VV1ProfileBadgesGet200Response) SetData(v []VVUserBadge) {
	o.Data = v
}

func (o VV1ProfileBadgesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1ProfileBadgesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VV1ProfileBadgesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1ProfileBadgesGet200Response := _VV1ProfileBadgesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1ProfileBadgesGet200Response)

	if err != nil {
		return err
	}

	*o = VV1ProfileBadgesGet200Response(varVV1ProfileBadgesGet200Response)

	return err
}

type NullableVV1ProfileBadgesGet200Response struct {
	value *VV1ProfileBadgesGet200Response
	isSet bool
}

func (v NullableVV1ProfileBadgesGet200Response) Get() *VV1ProfileBadgesGet200Response {
	return v.value
}

func (v *NullableVV1ProfileBadgesGet200Response) Set(val *VV1ProfileBadgesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1ProfileBadgesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1ProfileBadgesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1ProfileBadgesGet200Response(val *VV1ProfileBadgesGet200Response) *NullableVV1ProfileBadgesGet200Response {
	return &NullableVV1ProfileBadgesGet200Response{value: val, isSet: true}
}

func (v NullableVV1ProfileBadgesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1ProfileBadgesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


