/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1ProfileTokensPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1ProfileTokensPost201Response{}

// VV1ProfileTokensPost201Response struct for VV1ProfileTokensPost201Response
type VV1ProfileTokensPost201Response struct {
	Data VVTokenCreated `json:"data"`
}

type _VV1ProfileTokensPost201Response VV1ProfileTokensPost201Response

// NewVV1ProfileTokensPost201Response instantiates a new VV1ProfileTokensPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1ProfileTokensPost201Response(data VVTokenCreated) *VV1ProfileTokensPost201Response {
	this := VV1ProfileTokensPost201Response{}
	this.Data = data
	return &this
}

// NewVV1ProfileTokensPost201ResponseWithDefaults instantiates a new VV1ProfileTokensPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1ProfileTokensPost201ResponseWithDefaults() *VV1ProfileTokensPost201Response {
	this := VV1ProfileTokensPost201Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1ProfileTokensPost201Response) GetData() VVTokenCreated {
	if o == nil {
		var ret VVTokenCreated
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1ProfileTokensPost201Response) GetDataOk() (*VVTokenCreated, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VV1ProfileTokensPost201Response) SetData(v VVTokenCreated) {
	o.Data = v
}

func (o VV1ProfileTokensPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1ProfileTokensPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VV1ProfileTokensPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1ProfileTokensPost201Response := _VV1ProfileTokensPost201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1ProfileTokensPost201Response)

	if err != nil {
		return err
	}

	*o = VV1ProfileTokensPost201Response(varVV1ProfileTokensPost201Response)

	return err
}

type NullableVV1ProfileTokensPost201Response struct {
	value *VV1ProfileTokensPost201Response
	isSet bool
}

func (v NullableVV1ProfileTokensPost201Response) Get() *VV1ProfileTokensPost201Response {
	return v.value
}

func (v *NullableVV1ProfileTokensPost201Response) Set(val *VV1ProfileTokensPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1ProfileTokensPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1ProfileTokensPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1ProfileTokensPost201Response(val *VV1ProfileTokensPost201Response) *NullableVV1ProfileTokensPost201Response {
	return &NullableVV1ProfileTokensPost201Response{value: val, isSet: true}
}

func (v NullableVV1ProfileTokensPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1ProfileTokensPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


