/*
Tampa Events API

Community events aggregation API for Tampa Bay tech meetups and events

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VServiceStatusGet200ResponseGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VServiceStatusGet200ResponseGroupsInner{}

// VServiceStatusGet200ResponseGroupsInner struct for VServiceStatusGet200ResponseGroupsInner
type VServiceStatusGet200ResponseGroupsInner struct {
	Urlname string `json:"urlname"`
	Platform string `json:"platform"`
}

type _VServiceStatusGet200ResponseGroupsInner VServiceStatusGet200ResponseGroupsInner

// NewVServiceStatusGet200ResponseGroupsInner instantiates a new VServiceStatusGet200ResponseGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVServiceStatusGet200ResponseGroupsInner(urlname string, platform string) *VServiceStatusGet200ResponseGroupsInner {
	this := VServiceStatusGet200ResponseGroupsInner{}
	this.Urlname = urlname
	this.Platform = platform
	return &this
}

// NewVServiceStatusGet200ResponseGroupsInnerWithDefaults instantiates a new VServiceStatusGet200ResponseGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVServiceStatusGet200ResponseGroupsInnerWithDefaults() *VServiceStatusGet200ResponseGroupsInner {
	this := VServiceStatusGet200ResponseGroupsInner{}
	return &this
}

// GetUrlname returns the Urlname field value
func (o *VServiceStatusGet200ResponseGroupsInner) GetUrlname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Urlname
}

// GetUrlnameOk returns a tuple with the Urlname field value
// and a boolean to check if the value has been set.
func (o *VServiceStatusGet200ResponseGroupsInner) GetUrlnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Urlname, true
}

// SetUrlname sets field value
func (o *VServiceStatusGet200ResponseGroupsInner) SetUrlname(v string) {
	o.Urlname = v
}

// GetPlatform returns the Platform field value
func (o *VServiceStatusGet200ResponseGroupsInner) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *VServiceStatusGet200ResponseGroupsInner) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *VServiceStatusGet200ResponseGroupsInner) SetPlatform(v string) {
	o.Platform = v
}

func (o VServiceStatusGet200ResponseGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VServiceStatusGet200ResponseGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["urlname"] = o.Urlname
	toSerialize["platform"] = o.Platform
	return toSerialize, nil
}

func (o *VServiceStatusGet200ResponseGroupsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"urlname",
		"platform",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVServiceStatusGet200ResponseGroupsInner := _VServiceStatusGet200ResponseGroupsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVServiceStatusGet200ResponseGroupsInner)

	if err != nil {
		return err
	}

	*o = VServiceStatusGet200ResponseGroupsInner(varVServiceStatusGet200ResponseGroupsInner)

	return err
}

type NullableVServiceStatusGet200ResponseGroupsInner struct {
	value *VServiceStatusGet200ResponseGroupsInner
	isSet bool
}

func (v NullableVServiceStatusGet200ResponseGroupsInner) Get() *VServiceStatusGet200ResponseGroupsInner {
	return v.value
}

func (v *NullableVServiceStatusGet200ResponseGroupsInner) Set(val *VServiceStatusGet200ResponseGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableVServiceStatusGet200ResponseGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableVServiceStatusGet200ResponseGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVServiceStatusGet200ResponseGroupsInner(val *VServiceStatusGet200ResponseGroupsInner) *NullableVServiceStatusGet200ResponseGroupsInner {
	return &NullableVServiceStatusGet200ResponseGroupsInner{value: val, isSet: true}
}

func (v NullableVServiceStatusGet200ResponseGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVServiceStatusGet200ResponseGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


