/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1ProfileEntitlementsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1ProfileEntitlementsGet200Response{}

// VV1ProfileEntitlementsGet200Response struct for VV1ProfileEntitlementsGet200Response
type VV1ProfileEntitlementsGet200Response struct {
	Data []VVUserEntitlement `json:"data"`
}

type _VV1ProfileEntitlementsGet200Response VV1ProfileEntitlementsGet200Response

// NewVV1ProfileEntitlementsGet200Response instantiates a new VV1ProfileEntitlementsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1ProfileEntitlementsGet200Response(data []VVUserEntitlement) *VV1ProfileEntitlementsGet200Response {
	this := VV1ProfileEntitlementsGet200Response{}
	this.Data = data
	return &this
}

// NewVV1ProfileEntitlementsGet200ResponseWithDefaults instantiates a new VV1ProfileEntitlementsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1ProfileEntitlementsGet200ResponseWithDefaults() *VV1ProfileEntitlementsGet200Response {
	this := VV1ProfileEntitlementsGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VV1ProfileEntitlementsGet200Response) GetData() []VVUserEntitlement {
	if o == nil {
		var ret []VVUserEntitlement
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VV1ProfileEntitlementsGet200Response) GetDataOk() ([]VVUserEntitlement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VV1ProfileEntitlementsGet200Response) SetData(v []VVUserEntitlement) {
	o.Data = v
}

func (o VV1ProfileEntitlementsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1ProfileEntitlementsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VV1ProfileEntitlementsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1ProfileEntitlementsGet200Response := _VV1ProfileEntitlementsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1ProfileEntitlementsGet200Response)

	if err != nil {
		return err
	}

	*o = VV1ProfileEntitlementsGet200Response(varVV1ProfileEntitlementsGet200Response)

	return err
}

type NullableVV1ProfileEntitlementsGet200Response struct {
	value *VV1ProfileEntitlementsGet200Response
	isSet bool
}

func (v NullableVV1ProfileEntitlementsGet200Response) Get() *VV1ProfileEntitlementsGet200Response {
	return v.value
}

func (v *NullableVV1ProfileEntitlementsGet200Response) Set(val *VV1ProfileEntitlementsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1ProfileEntitlementsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1ProfileEntitlementsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1ProfileEntitlementsGet200Response(val *VV1ProfileEntitlementsGet200Response) *NullableVV1ProfileEntitlementsGet200Response {
	return &NullableVV1ProfileEntitlementsGet200Response{value: val, isSet: true}
}

func (v NullableVV1ProfileEntitlementsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1ProfileEntitlementsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


