/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1FavoritesGroupSlugPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1FavoritesGroupSlugPost200ResponseData{}

// VV1FavoritesGroupSlugPost200ResponseData struct for VV1FavoritesGroupSlugPost200ResponseData
type VV1FavoritesGroupSlugPost200ResponseData struct {
	AlreadyFavorited bool `json:"alreadyFavorited"`
}

type _VV1FavoritesGroupSlugPost200ResponseData VV1FavoritesGroupSlugPost200ResponseData

// NewVV1FavoritesGroupSlugPost200ResponseData instantiates a new VV1FavoritesGroupSlugPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1FavoritesGroupSlugPost200ResponseData(alreadyFavorited bool) *VV1FavoritesGroupSlugPost200ResponseData {
	this := VV1FavoritesGroupSlugPost200ResponseData{}
	this.AlreadyFavorited = alreadyFavorited
	return &this
}

// NewVV1FavoritesGroupSlugPost200ResponseDataWithDefaults instantiates a new VV1FavoritesGroupSlugPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1FavoritesGroupSlugPost200ResponseDataWithDefaults() *VV1FavoritesGroupSlugPost200ResponseData {
	this := VV1FavoritesGroupSlugPost200ResponseData{}
	return &this
}

// GetAlreadyFavorited returns the AlreadyFavorited field value
func (o *VV1FavoritesGroupSlugPost200ResponseData) GetAlreadyFavorited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlreadyFavorited
}

// GetAlreadyFavoritedOk returns a tuple with the AlreadyFavorited field value
// and a boolean to check if the value has been set.
func (o *VV1FavoritesGroupSlugPost200ResponseData) GetAlreadyFavoritedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlreadyFavorited, true
}

// SetAlreadyFavorited sets field value
func (o *VV1FavoritesGroupSlugPost200ResponseData) SetAlreadyFavorited(v bool) {
	o.AlreadyFavorited = v
}

func (o VV1FavoritesGroupSlugPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1FavoritesGroupSlugPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alreadyFavorited"] = o.AlreadyFavorited
	return toSerialize, nil
}

func (o *VV1FavoritesGroupSlugPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alreadyFavorited",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1FavoritesGroupSlugPost200ResponseData := _VV1FavoritesGroupSlugPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1FavoritesGroupSlugPost200ResponseData)

	if err != nil {
		return err
	}

	*o = VV1FavoritesGroupSlugPost200ResponseData(varVV1FavoritesGroupSlugPost200ResponseData)

	return err
}

type NullableVV1FavoritesGroupSlugPost200ResponseData struct {
	value *VV1FavoritesGroupSlugPost200ResponseData
	isSet bool
}

func (v NullableVV1FavoritesGroupSlugPost200ResponseData) Get() *VV1FavoritesGroupSlugPost200ResponseData {
	return v.value
}

func (v *NullableVV1FavoritesGroupSlugPost200ResponseData) Set(val *VV1FavoritesGroupSlugPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1FavoritesGroupSlugPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1FavoritesGroupSlugPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1FavoritesGroupSlugPost200ResponseData(val *VV1FavoritesGroupSlugPost200ResponseData) *NullableVV1FavoritesGroupSlugPost200ResponseData {
	return &NullableVV1FavoritesGroupSlugPost200ResponseData{value: val, isSet: true}
}

func (v NullableVV1FavoritesGroupSlugPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1FavoritesGroupSlugPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


