/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VV1UsersUsernameFollowPost201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VV1UsersUsernameFollowPost201ResponseData{}

// VV1UsersUsernameFollowPost201ResponseData struct for VV1UsersUsernameFollowPost201ResponseData
type VV1UsersUsernameFollowPost201ResponseData struct {
	Following bool `json:"following"`
}

type _VV1UsersUsernameFollowPost201ResponseData VV1UsersUsernameFollowPost201ResponseData

// NewVV1UsersUsernameFollowPost201ResponseData instantiates a new VV1UsersUsernameFollowPost201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVV1UsersUsernameFollowPost201ResponseData(following bool) *VV1UsersUsernameFollowPost201ResponseData {
	this := VV1UsersUsernameFollowPost201ResponseData{}
	this.Following = following
	return &this
}

// NewVV1UsersUsernameFollowPost201ResponseDataWithDefaults instantiates a new VV1UsersUsernameFollowPost201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVV1UsersUsernameFollowPost201ResponseDataWithDefaults() *VV1UsersUsernameFollowPost201ResponseData {
	this := VV1UsersUsernameFollowPost201ResponseData{}
	return &this
}

// GetFollowing returns the Following field value
func (o *VV1UsersUsernameFollowPost201ResponseData) GetFollowing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Following
}

// GetFollowingOk returns a tuple with the Following field value
// and a boolean to check if the value has been set.
func (o *VV1UsersUsernameFollowPost201ResponseData) GetFollowingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Following, true
}

// SetFollowing sets field value
func (o *VV1UsersUsernameFollowPost201ResponseData) SetFollowing(v bool) {
	o.Following = v
}

func (o VV1UsersUsernameFollowPost201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VV1UsersUsernameFollowPost201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["following"] = o.Following
	return toSerialize, nil
}

func (o *VV1UsersUsernameFollowPost201ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"following",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVV1UsersUsernameFollowPost201ResponseData := _VV1UsersUsernameFollowPost201ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVV1UsersUsernameFollowPost201ResponseData)

	if err != nil {
		return err
	}

	*o = VV1UsersUsernameFollowPost201ResponseData(varVV1UsersUsernameFollowPost201ResponseData)

	return err
}

type NullableVV1UsersUsernameFollowPost201ResponseData struct {
	value *VV1UsersUsernameFollowPost201ResponseData
	isSet bool
}

func (v NullableVV1UsersUsernameFollowPost201ResponseData) Get() *VV1UsersUsernameFollowPost201ResponseData {
	return v.value
}

func (v *NullableVV1UsersUsernameFollowPost201ResponseData) Set(val *VV1UsersUsernameFollowPost201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableVV1UsersUsernameFollowPost201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableVV1UsersUsernameFollowPost201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVV1UsersUsernameFollowPost201ResponseData(val *VV1UsersUsernameFollowPost201ResponseData) *NullableVV1UsersUsernameFollowPost201ResponseData {
	return &NullableVV1UsersUsernameFollowPost201ResponseData{value: val, isSet: true}
}

func (v NullableVV1UsersUsernameFollowPost201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVV1UsersUsernameFollowPost201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


