/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V20260125SchemasGet200ResponseSchemasInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V20260125SchemasGet200ResponseSchemasInner{}

// V20260125SchemasGet200ResponseSchemasInner struct for V20260125SchemasGet200ResponseSchemasInner
type V20260125SchemasGet200ResponseSchemasInner struct {
	Name string `json:"name"`
	Title string `json:"title"`
	Description string `json:"description"`
	Url string `json:"url"`
}

type _V20260125SchemasGet200ResponseSchemasInner V20260125SchemasGet200ResponseSchemasInner

// NewV20260125SchemasGet200ResponseSchemasInner instantiates a new V20260125SchemasGet200ResponseSchemasInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV20260125SchemasGet200ResponseSchemasInner(name string, title string, description string, url string) *V20260125SchemasGet200ResponseSchemasInner {
	this := V20260125SchemasGet200ResponseSchemasInner{}
	this.Name = name
	this.Title = title
	this.Description = description
	this.Url = url
	return &this
}

// NewV20260125SchemasGet200ResponseSchemasInnerWithDefaults instantiates a new V20260125SchemasGet200ResponseSchemasInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV20260125SchemasGet200ResponseSchemasInnerWithDefaults() *V20260125SchemasGet200ResponseSchemasInner {
	this := V20260125SchemasGet200ResponseSchemasInner{}
	return &this
}

// GetName returns the Name field value
func (o *V20260125SchemasGet200ResponseSchemasInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V20260125SchemasGet200ResponseSchemasInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V20260125SchemasGet200ResponseSchemasInner) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *V20260125SchemasGet200ResponseSchemasInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *V20260125SchemasGet200ResponseSchemasInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *V20260125SchemasGet200ResponseSchemasInner) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value
func (o *V20260125SchemasGet200ResponseSchemasInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *V20260125SchemasGet200ResponseSchemasInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *V20260125SchemasGet200ResponseSchemasInner) SetDescription(v string) {
	o.Description = v
}

// GetUrl returns the Url field value
func (o *V20260125SchemasGet200ResponseSchemasInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *V20260125SchemasGet200ResponseSchemasInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *V20260125SchemasGet200ResponseSchemasInner) SetUrl(v string) {
	o.Url = v
}

func (o V20260125SchemasGet200ResponseSchemasInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V20260125SchemasGet200ResponseSchemasInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["description"] = o.Description
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *V20260125SchemasGet200ResponseSchemasInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"title",
		"description",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV20260125SchemasGet200ResponseSchemasInner := _V20260125SchemasGet200ResponseSchemasInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV20260125SchemasGet200ResponseSchemasInner)

	if err != nil {
		return err
	}

	*o = V20260125SchemasGet200ResponseSchemasInner(varV20260125SchemasGet200ResponseSchemasInner)

	return err
}

type NullableV20260125SchemasGet200ResponseSchemasInner struct {
	value *V20260125SchemasGet200ResponseSchemasInner
	isSet bool
}

func (v NullableV20260125SchemasGet200ResponseSchemasInner) Get() *V20260125SchemasGet200ResponseSchemasInner {
	return v.value
}

func (v *NullableV20260125SchemasGet200ResponseSchemasInner) Set(val *V20260125SchemasGet200ResponseSchemasInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV20260125SchemasGet200ResponseSchemasInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV20260125SchemasGet200ResponseSchemasInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV20260125SchemasGet200ResponseSchemasInner(val *V20260125SchemasGet200ResponseSchemasInner) *NullableV20260125SchemasGet200ResponseSchemasInner {
	return &NullableV20260125SchemasGet200ResponseSchemasInner{value: val, isSet: true}
}

func (v NullableV20260125SchemasGet200ResponseSchemasInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV20260125SchemasGet200ResponseSchemasInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


