/*
Tampa.dev Platform API

The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

API version: 2026-01-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tampaevents

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VUserBadge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VUserBadge{}

// VUserBadge struct for VUserBadge
type VUserBadge struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	// URL to the high-quality emoji image, or null if unavailable
	IconUrl string `json:"iconUrl"`
	Color string `json:"color"`
	Points float32 `json:"points"`
	AwardedAt string `json:"awardedAt"`
	Group VVUserBadgeGroup `json:"group"`
	Rarity VVUserBadgeRarity `json:"rarity"`
}

type _VUserBadge VUserBadge

// NewVUserBadge instantiates a new VUserBadge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVUserBadge(name string, slug string, description string, icon string, iconUrl string, color string, points float32, awardedAt string, group VVUserBadgeGroup, rarity VVUserBadgeRarity) *VUserBadge {
	this := VUserBadge{}
	this.Name = name
	this.Slug = slug
	this.Description = description
	this.Icon = icon
	this.IconUrl = iconUrl
	this.Color = color
	this.Points = points
	this.AwardedAt = awardedAt
	this.Group = group
	this.Rarity = rarity
	return &this
}

// NewVUserBadgeWithDefaults instantiates a new VUserBadge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVUserBadgeWithDefaults() *VUserBadge {
	this := VUserBadge{}
	return &this
}

// GetName returns the Name field value
func (o *VUserBadge) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VUserBadge) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *VUserBadge) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *VUserBadge) SetSlug(v string) {
	o.Slug = v
}

// GetDescription returns the Description field value
func (o *VUserBadge) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *VUserBadge) SetDescription(v string) {
	o.Description = v
}

// GetIcon returns the Icon field value
func (o *VUserBadge) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *VUserBadge) SetIcon(v string) {
	o.Icon = v
}

// GetIconUrl returns the IconUrl field value
func (o *VUserBadge) GetIconUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconUrl
}

// GetIconUrlOk returns a tuple with the IconUrl field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconUrl, true
}

// SetIconUrl sets field value
func (o *VUserBadge) SetIconUrl(v string) {
	o.IconUrl = v
}

// GetColor returns the Color field value
func (o *VUserBadge) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *VUserBadge) SetColor(v string) {
	o.Color = v
}

// GetPoints returns the Points field value
func (o *VUserBadge) GetPoints() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetPointsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *VUserBadge) SetPoints(v float32) {
	o.Points = v
}

// GetAwardedAt returns the AwardedAt field value
func (o *VUserBadge) GetAwardedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AwardedAt
}

// GetAwardedAtOk returns a tuple with the AwardedAt field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetAwardedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AwardedAt, true
}

// SetAwardedAt sets field value
func (o *VUserBadge) SetAwardedAt(v string) {
	o.AwardedAt = v
}

// GetGroup returns the Group field value
func (o *VUserBadge) GetGroup() VVUserBadgeGroup {
	if o == nil {
		var ret VVUserBadgeGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetGroupOk() (*VVUserBadgeGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *VUserBadge) SetGroup(v VVUserBadgeGroup) {
	o.Group = v
}

// GetRarity returns the Rarity field value
func (o *VUserBadge) GetRarity() VVUserBadgeRarity {
	if o == nil {
		var ret VVUserBadgeRarity
		return ret
	}

	return o.Rarity
}

// GetRarityOk returns a tuple with the Rarity field value
// and a boolean to check if the value has been set.
func (o *VUserBadge) GetRarityOk() (*VVUserBadgeRarity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rarity, true
}

// SetRarity sets field value
func (o *VUserBadge) SetRarity(v VVUserBadgeRarity) {
	o.Rarity = v
}

func (o VUserBadge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VUserBadge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["description"] = o.Description
	toSerialize["icon"] = o.Icon
	toSerialize["iconUrl"] = o.IconUrl
	toSerialize["color"] = o.Color
	toSerialize["points"] = o.Points
	toSerialize["awardedAt"] = o.AwardedAt
	toSerialize["group"] = o.Group
	toSerialize["rarity"] = o.Rarity
	return toSerialize, nil
}

func (o *VUserBadge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slug",
		"description",
		"icon",
		"iconUrl",
		"color",
		"points",
		"awardedAt",
		"group",
		"rarity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVUserBadge := _VUserBadge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVUserBadge)

	if err != nil {
		return err
	}

	*o = VUserBadge(varVUserBadge)

	return err
}

type NullableVUserBadge struct {
	value *VUserBadge
	isSet bool
}

func (v NullableVUserBadge) Get() *VUserBadge {
	return v.value
}

func (v *NullableVUserBadge) Set(val *VUserBadge) {
	v.value = val
	v.isSet = true
}

func (v NullableVUserBadge) IsSet() bool {
	return v.isSet
}

func (v *NullableVUserBadge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVUserBadge(val *VUserBadge) *NullableVUserBadge {
	return &NullableVUserBadge{value: val, isSet: true}
}

func (v NullableVUserBadge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVUserBadge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


