=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TampaEventsAPI::20260125SchemasNameGet404Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TampaEventsAPI::20260125SchemasNameGet404Response do
  #let(:instance) { TampaEventsAPI::20260125SchemasNameGet404Response.new }

  describe 'test an instance of 20260125SchemasNameGet404Response' do
    it 'should create an instance of 20260125SchemasNameGet404Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TampaEventsAPI::20260125SchemasNameGet404Response)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "available"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
