=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TampaEventsAPI::VServiceStatusGet200ResponsePlatformsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TampaEventsAPI::VServiceStatusGet200ResponsePlatformsInner do
  #let(:instance) { TampaEventsAPI::VServiceStatusGet200ResponsePlatformsInner.new }

  describe 'test an instance of VServiceStatusGet200ResponsePlatformsInner' do
    it 'should create an instance of VServiceStatusGet200ResponsePlatformsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TampaEventsAPI::VServiceStatusGet200ResponsePlatformsInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "configured"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
