=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TampaEventsAPI::VV1UsersUsernameFollowPost200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TampaEventsAPI::VV1UsersUsernameFollowPost200ResponseData do
  #let(:instance) { TampaEventsAPI::VV1UsersUsernameFollowPost200ResponseData.new }

  describe 'test an instance of VV1UsersUsernameFollowPost200ResponseData' do
    it 'should create an instance of VV1UsersUsernameFollowPost200ResponseData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TampaEventsAPI::VV1UsersUsernameFollowPost200ResponseData)
    end
  end

  describe 'test attribute "already_following"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Boolean', ["true"])
      # validator.allowable_values.each do |value|
      #   expect { instance.already_following = value }.not_to raise_error
      # end
    end
  end

end
