=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TampaEventsAPI::ClaimsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClaimsApi' do
  before do
    # run before each test
    @api_instance = TampaEventsAPI::ClaimsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClaimsApi' do
    it 'should create an instance of ClaimsApi' do
      expect(@api_instance).to be_instance_of(TampaEventsAPI::ClaimsApi)
    end
  end

  # unit tests for v1_claim_code_get
  # Get badge claim info
  # Returns information about a badge claim link. No authentication required.
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [VV1ClaimCodeGet200Response]
  describe 'v1_claim_code_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_claim_code_post
  # Claim a badge
  # Claims a badge using a claim link code. Requires authentication.
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [VV1ClaimCodePost201Response]
  describe 'v1_claim_code_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
