=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TampaEventsAPI::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = TampaEventsAPI::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(TampaEventsAPI::UserApi)
    end
  end

  # unit tests for v1_me_get
  # Get current user identity
  # Returns basic identity information for the authenticated user. Email is included only if the &#x60;user:email&#x60; scope is granted.
  # @param [Hash] opts the optional parameters
  # @return [VV1MeGet200Response]
  describe 'v1_me_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_me_linked_accounts_get
  # List linked OAuth accounts
  # Returns the OAuth providers (GitHub, Discord, etc.) connected to the authenticated user&#39;s account.
  # @param [Hash] opts the optional parameters
  # @return [VV1MeLinkedAccountsGet200Response]
  describe 'v1_me_linked_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_achievements_get
  # Get achievement progress
  # Returns all achievements with the authenticated user&#39;s progress toward each.
  # @param [Hash] opts the optional parameters
  # @return [VV1ProfileAchievementsGet200Response]
  describe 'v1_profile_achievements_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_get
  # Get current user profile
  # Returns the full profile for the authenticated user including bio, social links, and settings.
  # @param [Hash] opts the optional parameters
  # @return [VV1ProfileGet200Response]
  describe 'v1_profile_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_patch
  # Update current user profile
  # Updates the authenticated user&#39;s profile fields. Only provided fields are updated.
  # @param [Hash] opts the optional parameters
  # @option opts [VUpdateProfileRequest] :v_update_profile_request 
  # @return [VV1ProfileGet200Response]
  describe 'v1_profile_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_portfolio_get
  # List portfolio items
  # Returns all portfolio items for the authenticated user, ordered by sort order.
  # @param [Hash] opts the optional parameters
  # @return [VV1ProfilePortfolioGet200Response]
  describe 'v1_profile_portfolio_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_portfolio_id_delete
  # Delete portfolio item
  # Permanently removes a portfolio item from the authenticated user&#39;s profile.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_profile_portfolio_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_portfolio_id_patch
  # Update portfolio item
  # Updates an existing portfolio item. Only provided fields are changed.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [VPortfolioItemUpdateRequest] :v_portfolio_item_update_request 
  # @return [VV1ProfilePortfolioPost201Response]
  describe 'v1_profile_portfolio_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_portfolio_post
  # Create portfolio item
  # Adds a new portfolio item to the authenticated user&#39;s profile.
  # @param [Hash] opts the optional parameters
  # @option opts [VPortfolioItemRequest] :v_portfolio_item_request 
  # @return [VV1ProfilePortfolioPost201Response]
  describe 'v1_profile_portfolio_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_tokens_get
  # List personal access tokens
  # Returns all personal access tokens for the authenticated user. Token values are not included.
  # @param [Hash] opts the optional parameters
  # @return [VV1ProfileTokensGet200Response]
  describe 'v1_profile_tokens_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_tokens_id_delete
  # Revoke personal access token
  # Permanently revokes a personal access token. The token can no longer be used for authentication.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_profile_tokens_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_profile_tokens_post
  # Create personal access token
  # Creates a new personal access token. The full token value is returned only once in the response -- store it securely.
  # @param [Hash] opts the optional parameters
  # @option opts [VCreateTokenRequest] :v_create_token_request 
  # @return [VV1ProfileTokensPost201Response]
  describe 'v1_profile_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
