=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TampaEventsAPI::WidgetsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WidgetsApi' do
  before do
    # run before each test
    @api_instance = TampaEventsAPI::WidgetsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WidgetsApi' do
    it 'should create an instance of WidgetsApi' do
      expect(@api_instance).to be_instance_of(TampaEventsAPI::WidgetsApi)
    end
  end

  # unit tests for widget_carousel_get
  # Carousel HTML widget
  # Returns an HTML carousel widget showing upcoming events
  # @param [Hash] opts the optional parameters
  # @option opts [String] :groups 
  # @return [String]
  describe 'widget_carousel_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for widget_next_event_get
  # Next event HTML widget
  # Returns an HTML widget showing the next upcoming event
  # @param [Hash] opts the optional parameters
  # @option opts [String] :groups 
  # @return [String]
  describe 'widget_next_event_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
