# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.vv1_events_event_id_rsvp_post201_response import VV1EventsEventIdRsvpPost201Response

class TestVV1EventsEventIdRsvpPost201Response(unittest.TestCase):
    """VV1EventsEventIdRsvpPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VV1EventsEventIdRsvpPost201Response:
        """Test VV1EventsEventIdRsvpPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VV1EventsEventIdRsvpPost201Response`
        """
        model = VV1EventsEventIdRsvpPost201Response()
        if include_optional:
            return VV1EventsEventIdRsvpPost201Response(
                data = tampa_events_api.models.rsvp.Rsvp(
                    id = '', 
                    event_id = '', 
                    status = 'confirmed', 
                    rsvp_at = '', 
                    waitlist_position = 1.337, )
            )
        else:
            return VV1EventsEventIdRsvpPost201Response(
                data = tampa_events_api.models.rsvp.Rsvp(
                    id = '', 
                    event_id = '', 
                    status = 'confirmed', 
                    rsvp_at = '', 
                    waitlist_position = 1.337, ),
        )
        """

    def testVV1EventsEventIdRsvpPost201Response(self):
        """Test VV1EventsEventIdRsvpPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
