# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.vv1_claim_code_get200_response import VV1ClaimCodeGet200Response

class TestVV1ClaimCodeGet200Response(unittest.TestCase):
    """VV1ClaimCodeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VV1ClaimCodeGet200Response:
        """Test VV1ClaimCodeGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VV1ClaimCodeGet200Response`
        """
        model = VV1ClaimCodeGet200Response()
        if include_optional:
            return VV1ClaimCodeGet200Response(
                data = tampa_events_api.models.claim_info.ClaimInfo(
                    badge = tampa_events_api.models.claim_info_badge.ClaimInfo_badge(
                        name = '', 
                        slug = '', 
                        description = '', 
                        icon = '', 
                        color = '', 
                        points = 1.337, ), 
                    group = tampa_events_api.models.claim_info_group.ClaimInfo_group(
                        name = '', 
                        urlname = '', 
                        photo_url = '', ), 
                    claimable = True, 
                    reason = '', )
            )
        else:
            return VV1ClaimCodeGet200Response(
                data = tampa_events_api.models.claim_info.ClaimInfo(
                    badge = tampa_events_api.models.claim_info_badge.ClaimInfo_badge(
                        name = '', 
                        slug = '', 
                        description = '', 
                        icon = '', 
                        color = '', 
                        points = 1.337, ), 
                    group = tampa_events_api.models.claim_info_group.ClaimInfo_group(
                        name = '', 
                        urlname = '', 
                        photo_url = '', ), 
                    claimable = True, 
                    reason = '', ),
        )
        """

    def testVV1ClaimCodeGet200Response(self):
        """Test VV1ClaimCodeGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
