# coding: utf-8

"""
    Tampa Events API

    Community events aggregation API for Tampa Bay tech meetups and events

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.service_status_get200_response_aggregation import ServiceStatusGet200ResponseAggregation

class TestServiceStatusGet200ResponseAggregation(unittest.TestCase):
    """ServiceStatusGet200ResponseAggregation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceStatusGet200ResponseAggregation:
        """Test ServiceStatusGet200ResponseAggregation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceStatusGet200ResponseAggregation`
        """
        model = ServiceStatusGet200ResponseAggregation()
        if include_optional:
            return ServiceStatusGet200ResponseAggregation(
                last_run_at = '',
                duration_ms = 1.337,
                groups_processed = 1.337,
                groups_failed = 1.337,
                data_hash = '',
                errors = [
                    ''
                    ]
            )
        else:
            return ServiceStatusGet200ResponseAggregation(
                last_run_at = '',
                duration_ms = 1.337,
                groups_processed = 1.337,
                groups_failed = 1.337,
                data_hash = '',
                errors = [
                    ''
                    ],
        )
        """

    def testServiceStatusGet200ResponseAggregation(self):
        """Test ServiceStatusGet200ResponseAggregation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
