# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.v_user_profile import VUserProfile

class TestVUserProfile(unittest.TestCase):
    """VUserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VUserProfile:
        """Test VUserProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VUserProfile`
        """
        model = VUserProfile()
        if include_optional:
            return VUserProfile(
                id = '',
                name = '',
                username = '',
                avatar_url = '',
                hero_image_url = '',
                theme_color = '',
                bio = '',
                location = '',
                social_links = [
                    ''
                    ],
                role = '',
                profile_visibility = 'public',
                show_achievements = True,
                created_at = '',
                email = ''
            )
        else:
            return VUserProfile(
                id = '',
                name = '',
                username = '',
                avatar_url = '',
                hero_image_url = '',
                theme_color = '',
                bio = '',
                location = '',
                social_links = [
                    ''
                    ],
                role = '',
                profile_visibility = 'public',
                show_achievements = True,
                created_at = '',
        )
        """

    def testVUserProfile(self):
        """Test VUserProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
