# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.vv1_users_username_follow_post200_response_data import VV1UsersUsernameFollowPost200ResponseData

class TestVV1UsersUsernameFollowPost200ResponseData(unittest.TestCase):
    """VV1UsersUsernameFollowPost200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VV1UsersUsernameFollowPost200ResponseData:
        """Test VV1UsersUsernameFollowPost200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VV1UsersUsernameFollowPost200ResponseData`
        """
        model = VV1UsersUsernameFollowPost200ResponseData()
        if include_optional:
            return VV1UsersUsernameFollowPost200ResponseData(
                already_following = true
            )
        else:
            return VV1UsersUsernameFollowPost200ResponseData(
                already_following = true,
        )
        """

    def testVV1UsersUsernameFollowPost200ResponseData(self):
        """Test VV1UsersUsernameFollowPost200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
