# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.vv1_me_get200_response import VV1MeGet200Response

class TestVV1MeGet200Response(unittest.TestCase):
    """VV1MeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VV1MeGet200Response:
        """Test VV1MeGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VV1MeGet200Response`
        """
        model = VV1MeGet200Response()
        if include_optional:
            return VV1MeGet200Response(
                data = tampa_events_api.models.user_basic.UserBasic(
                    id = '', 
                    name = '', 
                    avatar_url = '', 
                    username = '', 
                    email = '', )
            )
        else:
            return VV1MeGet200Response(
                data = tampa_events_api.models.user_basic.UserBasic(
                    id = '', 
                    name = '', 
                    avatar_url = '', 
                    username = '', 
                    email = '', ),
        )
        """

    def testVV1MeGet200Response(self):
        """Test VV1MeGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
