# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.v_rsvp_summary import VRsvpSummary

class TestVRsvpSummary(unittest.TestCase):
    """VRsvpSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VRsvpSummary:
        """Test VRsvpSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VRsvpSummary`
        """
        model = VRsvpSummary()
        if include_optional:
            return VRsvpSummary(
                total = 1.337,
                confirmed = 1.337,
                waitlisted = 1.337,
                cancelled = 1.337,
                capacity = 1.337
            )
        else:
            return VRsvpSummary(
                total = 1.337,
                confirmed = 1.337,
                waitlisted = 1.337,
                cancelled = 1.337,
                capacity = 1.337,
        )
        """

    def testVRsvpSummary(self):
        """Test VRsvpSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
