# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.api.scopes_api import ScopesApi


class TestScopesApi(unittest.TestCase):
    """ScopesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScopesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_scopes_get(self) -> None:
        """Test case for v1_scopes_get

        List OAuth scopes
        """
        pass


if __name__ == '__main__':
    unittest.main()
