# coding: utf-8

"""
    Tampa Events API

    Community events aggregation API for Tampa Bay tech meetups and events

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tampa_events_api.models.v_service_status_get200_response import VServiceStatusGet200Response

class TestVServiceStatusGet200Response(unittest.TestCase):
    """VServiceStatusGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VServiceStatusGet200Response:
        """Test VServiceStatusGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VServiceStatusGet200Response`
        """
        model = VServiceStatusGet200Response()
        if include_optional:
            return VServiceStatusGet200Response(
                platforms = [
                    tampa_events_api.models._service_status_get_200_response_platforms_inner._service_status_get_200_response_platforms_inner(
                        name = '', 
                        configured = True, )
                    ],
                groups = [
                    tampa_events_api.models._service_status_get_200_response_groups_inner._service_status_get_200_response_groups_inner(
                        urlname = '', 
                        platform = '', )
                    ],
                total_groups = 1.337,
                aggregation = tampa_events_api.models._service_status_get_200_response_aggregation._service_status_get_200_response_aggregation(
                    last_run_at = '', 
                    duration_ms = 1.337, 
                    groups_processed = 1.337, 
                    groups_failed = 1.337, 
                    data_hash = '', 
                    errors = [
                        ''
                        ], )
            )
        else:
            return VServiceStatusGet200Response(
                platforms = [
                    tampa_events_api.models._service_status_get_200_response_platforms_inner._service_status_get_200_response_platforms_inner(
                        name = '', 
                        configured = True, )
                    ],
                groups = [
                    tampa_events_api.models._service_status_get_200_response_groups_inner._service_status_get_200_response_groups_inner(
                        urlname = '', 
                        platform = '', )
                    ],
                total_groups = 1.337,
                aggregation = tampa_events_api.models._service_status_get_200_response_aggregation._service_status_get_200_response_aggregation(
                    last_run_at = '', 
                    duration_ms = 1.337, 
                    groups_processed = 1.337, 
                    groups_failed = 1.337, 
                    data_hash = '', 
                    errors = [
                        ''
                        ], ),
        )
        """

    def testVServiceStatusGet200Response(self):
        """Test VServiceStatusGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
