# coding: utf-8

"""
    Tampa.dev Platform API

    The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

    The version of the OpenAPI document: 2026-01-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from tampa_events_api.models.v20260125_groups_get200_response_inner_social_links import V20260125GroupsGet200ResponseInnerSocialLinks
from typing import Optional, Set
from typing_extensions import Self

class V20260125GroupsGet200ResponseInner(BaseModel):
    """
    V20260125GroupsGet200ResponseInner
    """ # noqa: E501
    id: StrictStr
    urlname: StrictStr
    name: StrictStr
    description: StrictStr
    link: StrictStr
    website: StrictStr
    platform: StrictStr
    member_count: Union[StrictFloat, StrictInt] = Field(alias="memberCount")
    photo_url: StrictStr = Field(alias="photoUrl")
    is_featured: StrictBool = Field(alias="isFeatured")
    display_on_site: StrictBool = Field(alias="displayOnSite")
    tags: List[StrictStr]
    social_links: V20260125GroupsGet200ResponseInnerSocialLinks = Field(alias="socialLinks")
    favorites_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="favoritesCount")
    __properties: ClassVar[List[str]] = ["id", "urlname", "name", "description", "link", "website", "platform", "memberCount", "photoUrl", "isFeatured", "displayOnSite", "tags", "socialLinks", "favoritesCount"]

    @field_validator('platform')
    def platform_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['meetup', 'eventbrite', 'luma']):
            raise ValueError("must be one of enum values ('meetup', 'eventbrite', 'luma')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V20260125GroupsGet200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of social_links
        if self.social_links:
            _dict['socialLinks'] = self.social_links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V20260125GroupsGet200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "urlname": obj.get("urlname"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "link": obj.get("link"),
            "website": obj.get("website"),
            "platform": obj.get("platform"),
            "memberCount": obj.get("memberCount"),
            "photoUrl": obj.get("photoUrl"),
            "isFeatured": obj.get("isFeatured"),
            "displayOnSite": obj.get("displayOnSite"),
            "tags": obj.get("tags"),
            "socialLinks": V20260125GroupsGet200ResponseInnerSocialLinks.from_dict(obj["socialLinks"]) if obj.get("socialLinks") is not None else None,
            "favoritesCount": obj.get("favoritesCount")
        })
        return _obj


