=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TampaEventsAPI
  class VAchievementProgress < ApiModelBase
    attr_accessor :key

    attr_accessor :name

    attr_accessor :description

    attr_accessor :icon

    attr_accessor :color

    attr_accessor :target_value

    attr_accessor :current_value

    attr_accessor :completed_at

    attr_accessor :badge_slug

    attr_accessor :hidden

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'key' => :'key',
        :'name' => :'name',
        :'description' => :'description',
        :'icon' => :'icon',
        :'color' => :'color',
        :'target_value' => :'targetValue',
        :'current_value' => :'currentValue',
        :'completed_at' => :'completedAt',
        :'badge_slug' => :'badgeSlug',
        :'hidden' => :'hidden'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'key' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'icon' => :'String',
        :'color' => :'String',
        :'target_value' => :'Float',
        :'current_value' => :'Float',
        :'completed_at' => :'String',
        :'badge_slug' => :'String',
        :'hidden' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TampaEventsAPI::VAchievementProgress` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TampaEventsAPI::VAchievementProgress`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      else
        self.key = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'icon')
        self.icon = attributes[:'icon']
      else
        self.icon = nil
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      else
        self.color = nil
      end

      if attributes.key?(:'target_value')
        self.target_value = attributes[:'target_value']
      else
        self.target_value = nil
      end

      if attributes.key?(:'current_value')
        self.current_value = attributes[:'current_value']
      else
        self.current_value = nil
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      else
        self.completed_at = nil
      end

      if attributes.key?(:'badge_slug')
        self.badge_slug = attributes[:'badge_slug']
      else
        self.badge_slug = nil
      end

      if attributes.key?(:'hidden')
        self.hidden = attributes[:'hidden']
      else
        self.hidden = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @key.nil?
        invalid_properties.push('invalid value for "key", key cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @icon.nil?
        invalid_properties.push('invalid value for "icon", icon cannot be nil.')
      end

      if @color.nil?
        invalid_properties.push('invalid value for "color", color cannot be nil.')
      end

      if @target_value.nil?
        invalid_properties.push('invalid value for "target_value", target_value cannot be nil.')
      end

      if @current_value.nil?
        invalid_properties.push('invalid value for "current_value", current_value cannot be nil.')
      end

      if @completed_at.nil?
        invalid_properties.push('invalid value for "completed_at", completed_at cannot be nil.')
      end

      if @badge_slug.nil?
        invalid_properties.push('invalid value for "badge_slug", badge_slug cannot be nil.')
      end

      if @hidden.nil?
        invalid_properties.push('invalid value for "hidden", hidden cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @key.nil?
      return false if @name.nil?
      return false if @description.nil?
      return false if @icon.nil?
      return false if @color.nil?
      return false if @target_value.nil?
      return false if @current_value.nil?
      return false if @completed_at.nil?
      return false if @badge_slug.nil?
      return false if @hidden.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] key Value to be assigned
    def key=(key)
      if key.nil?
        fail ArgumentError, 'key cannot be nil'
      end

      @key = key
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] icon Value to be assigned
    def icon=(icon)
      if icon.nil?
        fail ArgumentError, 'icon cannot be nil'
      end

      @icon = icon
    end

    # Custom attribute writer method with validation
    # @param [Object] color Value to be assigned
    def color=(color)
      if color.nil?
        fail ArgumentError, 'color cannot be nil'
      end

      @color = color
    end

    # Custom attribute writer method with validation
    # @param [Object] target_value Value to be assigned
    def target_value=(target_value)
      if target_value.nil?
        fail ArgumentError, 'target_value cannot be nil'
      end

      @target_value = target_value
    end

    # Custom attribute writer method with validation
    # @param [Object] current_value Value to be assigned
    def current_value=(current_value)
      if current_value.nil?
        fail ArgumentError, 'current_value cannot be nil'
      end

      @current_value = current_value
    end

    # Custom attribute writer method with validation
    # @param [Object] completed_at Value to be assigned
    def completed_at=(completed_at)
      if completed_at.nil?
        fail ArgumentError, 'completed_at cannot be nil'
      end

      @completed_at = completed_at
    end

    # Custom attribute writer method with validation
    # @param [Object] badge_slug Value to be assigned
    def badge_slug=(badge_slug)
      if badge_slug.nil?
        fail ArgumentError, 'badge_slug cannot be nil'
      end

      @badge_slug = badge_slug
    end

    # Custom attribute writer method with validation
    # @param [Object] hidden Value to be assigned
    def hidden=(hidden)
      if hidden.nil?
        fail ArgumentError, 'hidden cannot be nil'
      end

      @hidden = hidden
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          key == o.key &&
          name == o.name &&
          description == o.description &&
          icon == o.icon &&
          color == o.color &&
          target_value == o.target_value &&
          current_value == o.current_value &&
          completed_at == o.completed_at &&
          badge_slug == o.badge_slug &&
          hidden == o.hidden
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [key, name, description, icon, color, target_value, current_value, completed_at, badge_slug, hidden].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
