=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TampaEventsAPI
  class VUserEntitlement < ApiModelBase
    attr_accessor :id

    # Entitlement key (e.g., dev.tampa.group.create)
    attr_accessor :entitlement

    # ISO timestamp when entitlement was granted
    attr_accessor :granted_at

    # ISO timestamp when entitlement expires, or null if permanent
    attr_accessor :expires_at

    # How the entitlement was granted (e.g., admin, achievement)
    attr_accessor :source

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'entitlement' => :'entitlement',
        :'granted_at' => :'grantedAt',
        :'expires_at' => :'expiresAt',
        :'source' => :'source'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'entitlement' => :'String',
        :'granted_at' => :'String',
        :'expires_at' => :'String',
        :'source' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TampaEventsAPI::VUserEntitlement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TampaEventsAPI::VUserEntitlement`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'entitlement')
        self.entitlement = attributes[:'entitlement']
      else
        self.entitlement = nil
      end

      if attributes.key?(:'granted_at')
        self.granted_at = attributes[:'granted_at']
      else
        self.granted_at = nil
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @entitlement.nil?
        invalid_properties.push('invalid value for "entitlement", entitlement cannot be nil.')
      end

      if @granted_at.nil?
        invalid_properties.push('invalid value for "granted_at", granted_at cannot be nil.')
      end

      if @expires_at.nil?
        invalid_properties.push('invalid value for "expires_at", expires_at cannot be nil.')
      end

      if @source.nil?
        invalid_properties.push('invalid value for "source", source cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @entitlement.nil?
      return false if @granted_at.nil?
      return false if @expires_at.nil?
      return false if @source.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] entitlement Value to be assigned
    def entitlement=(entitlement)
      if entitlement.nil?
        fail ArgumentError, 'entitlement cannot be nil'
      end

      @entitlement = entitlement
    end

    # Custom attribute writer method with validation
    # @param [Object] granted_at Value to be assigned
    def granted_at=(granted_at)
      if granted_at.nil?
        fail ArgumentError, 'granted_at cannot be nil'
      end

      @granted_at = granted_at
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_at Value to be assigned
    def expires_at=(expires_at)
      if expires_at.nil?
        fail ArgumentError, 'expires_at cannot be nil'
      end

      @expires_at = expires_at
    end

    # Custom attribute writer method with validation
    # @param [Object] source Value to be assigned
    def source=(source)
      if source.nil?
        fail ArgumentError, 'source cannot be nil'
      end

      @source = source
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          entitlement == o.entitlement &&
          granted_at == o.granted_at &&
          expires_at == o.expires_at &&
          source == o.source
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, entitlement, granted_at, expires_at, source].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
