=begin
#Tampa.dev Platform API

#The Tampa.dev Platform API provides authenticated access to community data including user profiles, events, groups, badges, and more. Authenticate with Personal Access Tokens (PATs) or OAuth 2.0 bearer tokens. All authenticated endpoints are under `/v1/`.

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TampaEventsAPI
  class VUserProfile < ApiModelBase
    attr_accessor :id

    attr_accessor :name

    attr_accessor :username

    attr_accessor :avatar_url

    attr_accessor :hero_image_url

    attr_accessor :theme_color

    attr_accessor :bio

    attr_accessor :location

    attr_accessor :social_links

    attr_accessor :role

    attr_accessor :profile_visibility

    attr_accessor :show_achievements

    attr_accessor :created_at

    attr_accessor :email

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'username' => :'username',
        :'avatar_url' => :'avatarUrl',
        :'hero_image_url' => :'heroImageUrl',
        :'theme_color' => :'themeColor',
        :'bio' => :'bio',
        :'location' => :'location',
        :'social_links' => :'socialLinks',
        :'role' => :'role',
        :'profile_visibility' => :'profileVisibility',
        :'show_achievements' => :'showAchievements',
        :'created_at' => :'createdAt',
        :'email' => :'email'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'username' => :'String',
        :'avatar_url' => :'String',
        :'hero_image_url' => :'String',
        :'theme_color' => :'String',
        :'bio' => :'String',
        :'location' => :'String',
        :'social_links' => :'Array<String>',
        :'role' => :'String',
        :'profile_visibility' => :'String',
        :'show_achievements' => :'Boolean',
        :'created_at' => :'String',
        :'email' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TampaEventsAPI::VUserProfile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TampaEventsAPI::VUserProfile`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      else
        self.username = nil
      end

      if attributes.key?(:'avatar_url')
        self.avatar_url = attributes[:'avatar_url']
      else
        self.avatar_url = nil
      end

      if attributes.key?(:'hero_image_url')
        self.hero_image_url = attributes[:'hero_image_url']
      else
        self.hero_image_url = nil
      end

      if attributes.key?(:'theme_color')
        self.theme_color = attributes[:'theme_color']
      else
        self.theme_color = nil
      end

      if attributes.key?(:'bio')
        self.bio = attributes[:'bio']
      else
        self.bio = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      else
        self.location = nil
      end

      if attributes.key?(:'social_links')
        if (value = attributes[:'social_links']).is_a?(Array)
          self.social_links = value
        end
      else
        self.social_links = nil
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      else
        self.role = nil
      end

      if attributes.key?(:'profile_visibility')
        self.profile_visibility = attributes[:'profile_visibility']
      else
        self.profile_visibility = nil
      end

      if attributes.key?(:'show_achievements')
        self.show_achievements = attributes[:'show_achievements']
      else
        self.show_achievements = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @username.nil?
        invalid_properties.push('invalid value for "username", username cannot be nil.')
      end

      if @avatar_url.nil?
        invalid_properties.push('invalid value for "avatar_url", avatar_url cannot be nil.')
      end

      if @hero_image_url.nil?
        invalid_properties.push('invalid value for "hero_image_url", hero_image_url cannot be nil.')
      end

      if @theme_color.nil?
        invalid_properties.push('invalid value for "theme_color", theme_color cannot be nil.')
      end

      if @bio.nil?
        invalid_properties.push('invalid value for "bio", bio cannot be nil.')
      end

      if @location.nil?
        invalid_properties.push('invalid value for "location", location cannot be nil.')
      end

      if @social_links.nil?
        invalid_properties.push('invalid value for "social_links", social_links cannot be nil.')
      end

      if @role.nil?
        invalid_properties.push('invalid value for "role", role cannot be nil.')
      end

      if @profile_visibility.nil?
        invalid_properties.push('invalid value for "profile_visibility", profile_visibility cannot be nil.')
      end

      if @show_achievements.nil?
        invalid_properties.push('invalid value for "show_achievements", show_achievements cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @username.nil?
      return false if @avatar_url.nil?
      return false if @hero_image_url.nil?
      return false if @theme_color.nil?
      return false if @bio.nil?
      return false if @location.nil?
      return false if @social_links.nil?
      return false if @role.nil?
      return false if @profile_visibility.nil?
      profile_visibility_validator = EnumAttributeValidator.new('String', ["public", "private"])
      return false unless profile_visibility_validator.valid?(@profile_visibility)
      return false if @show_achievements.nil?
      return false if @created_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] username Value to be assigned
    def username=(username)
      if username.nil?
        fail ArgumentError, 'username cannot be nil'
      end

      @username = username
    end

    # Custom attribute writer method with validation
    # @param [Object] avatar_url Value to be assigned
    def avatar_url=(avatar_url)
      if avatar_url.nil?
        fail ArgumentError, 'avatar_url cannot be nil'
      end

      @avatar_url = avatar_url
    end

    # Custom attribute writer method with validation
    # @param [Object] hero_image_url Value to be assigned
    def hero_image_url=(hero_image_url)
      if hero_image_url.nil?
        fail ArgumentError, 'hero_image_url cannot be nil'
      end

      @hero_image_url = hero_image_url
    end

    # Custom attribute writer method with validation
    # @param [Object] theme_color Value to be assigned
    def theme_color=(theme_color)
      if theme_color.nil?
        fail ArgumentError, 'theme_color cannot be nil'
      end

      @theme_color = theme_color
    end

    # Custom attribute writer method with validation
    # @param [Object] bio Value to be assigned
    def bio=(bio)
      if bio.nil?
        fail ArgumentError, 'bio cannot be nil'
      end

      @bio = bio
    end

    # Custom attribute writer method with validation
    # @param [Object] location Value to be assigned
    def location=(location)
      if location.nil?
        fail ArgumentError, 'location cannot be nil'
      end

      @location = location
    end

    # Custom attribute writer method with validation
    # @param [Object] social_links Value to be assigned
    def social_links=(social_links)
      if social_links.nil?
        fail ArgumentError, 'social_links cannot be nil'
      end

      @social_links = social_links
    end

    # Custom attribute writer method with validation
    # @param [Object] role Value to be assigned
    def role=(role)
      if role.nil?
        fail ArgumentError, 'role cannot be nil'
      end

      @role = role
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] profile_visibility Object to be assigned
    def profile_visibility=(profile_visibility)
      validator = EnumAttributeValidator.new('String', ["public", "private"])
      unless validator.valid?(profile_visibility)
        fail ArgumentError, "invalid value for \"profile_visibility\", must be one of #{validator.allowable_values}."
      end
      @profile_visibility = profile_visibility
    end

    # Custom attribute writer method with validation
    # @param [Object] show_achievements Value to be assigned
    def show_achievements=(show_achievements)
      if show_achievements.nil?
        fail ArgumentError, 'show_achievements cannot be nil'
      end

      @show_achievements = show_achievements
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          username == o.username &&
          avatar_url == o.avatar_url &&
          hero_image_url == o.hero_image_url &&
          theme_color == o.theme_color &&
          bio == o.bio &&
          location == o.location &&
          social_links == o.social_links &&
          role == o.role &&
          profile_visibility == o.profile_visibility &&
          show_achievements == o.show_achievements &&
          created_at == o.created_at &&
          email == o.email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, username, avatar_url, hero_image_url, theme_color, bio, location, social_links, role, profile_visibility, show_achievements, created_at, email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
