=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'cgi'

module TampaEventsAPI
  class EventsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get all events
    # Returns a list of all upcoming events, optionally filtered by query parameters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :groups 
    # @option opts [String] :noonline 
    # @option opts [String] :within_hours 
    # @option opts [String] :within_days 
    # @option opts [String] :noempty 
    # @return [Array<20260125EventsGet200ResponseInner>]
    def call_20260125_events_get(opts = {})
      data, _status_code, _headers = call_20260125_events_get_with_http_info(opts)
      data
    end

    # Get all events
    # Returns a list of all upcoming events, optionally filtered by query parameters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :groups 
    # @option opts [String] :noonline 
    # @option opts [String] :within_hours 
    # @option opts [String] :within_days 
    # @option opts [String] :noempty 
    # @return [Array<(Array<20260125EventsGet200ResponseInner>, Integer, Hash)>] Array<20260125EventsGet200ResponseInner> data, response status code and response headers
    def call_20260125_events_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EventsApi.call_20260125_events_get ...'
      end
      # resource path
      local_var_path = '/2026-01-25/events'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'groups'] = opts[:'groups'] if !opts[:'groups'].nil?
      query_params[:'noonline'] = opts[:'noonline'] if !opts[:'noonline'].nil?
      query_params[:'within_hours'] = opts[:'within_hours'] if !opts[:'within_hours'].nil?
      query_params[:'within_days'] = opts[:'within_days'] if !opts[:'within_days'].nil?
      query_params[:'noempty'] = opts[:'noempty'] if !opts[:'noempty'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/plain']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<20260125EventsGet200ResponseInner>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"EventsApi.call_20260125_events_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EventsApi#call_20260125_events_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get next event per group
    # Returns one upcoming event for each group (the next event)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :groups 
    # @option opts [String] :noonline 
    # @option opts [String] :within_hours 
    # @option opts [String] :within_days 
    # @option opts [String] :noempty 
    # @return [Array<20260125EventsGet200ResponseInner>]
    def call_20260125_events_next_get(opts = {})
      data, _status_code, _headers = call_20260125_events_next_get_with_http_info(opts)
      data
    end

    # Get next event per group
    # Returns one upcoming event for each group (the next event)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :groups 
    # @option opts [String] :noonline 
    # @option opts [String] :within_hours 
    # @option opts [String] :within_days 
    # @option opts [String] :noempty 
    # @return [Array<(Array<20260125EventsGet200ResponseInner>, Integer, Hash)>] Array<20260125EventsGet200ResponseInner> data, response status code and response headers
    def call_20260125_events_next_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EventsApi.call_20260125_events_next_get ...'
      end
      # resource path
      local_var_path = '/2026-01-25/events/next'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'groups'] = opts[:'groups'] if !opts[:'groups'].nil?
      query_params[:'noonline'] = opts[:'noonline'] if !opts[:'noonline'].nil?
      query_params[:'within_hours'] = opts[:'within_hours'] if !opts[:'within_hours'].nil?
      query_params[:'within_days'] = opts[:'within_days'] if !opts[:'within_days'].nil?
      query_params[:'noempty'] = opts[:'noempty'] if !opts[:'noempty'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/plain']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<20260125EventsGet200ResponseInner>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"EventsApi.call_20260125_events_next_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EventsApi#call_20260125_events_next_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
