=begin
#Tampa Events API

#Community events aggregation API for Tampa Bay tech meetups and events

The version of the OpenAPI document: 2026-01-25

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'cgi'

module TampaEventsAPI
  class SchemasApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List all JSON schemas
    # Returns metadata about all available JSON schemas for the API models
    # @param [Hash] opts the optional parameters
    # @return [20260125SchemasGet200Response]
    def call_20260125_schemas_get(opts = {})
      data, _status_code, _headers = call_20260125_schemas_get_with_http_info(opts)
      data
    end

    # List all JSON schemas
    # Returns metadata about all available JSON schemas for the API models
    # @param [Hash] opts the optional parameters
    # @return [Array<(20260125SchemasGet200Response, Integer, Hash)>] 20260125SchemasGet200Response data, response status code and response headers
    def call_20260125_schemas_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SchemasApi.call_20260125_schemas_get ...'
      end
      # resource path
      local_var_path = '/2026-01-25/schemas'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || '20260125SchemasGet200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SchemasApi.call_20260125_schemas_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SchemasApi#call_20260125_schemas_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get specific JSON schema
    # Returns the JSON Schema for a specific model type
    # @param name [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def call_20260125_schemas_name_get(name, opts = {})
      data, _status_code, _headers = call_20260125_schemas_name_get_with_http_info(name, opts)
      data
    end

    # Get specific JSON schema
    # Returns the JSON Schema for a specific model type
    # @param name [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def call_20260125_schemas_name_get_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SchemasApi.call_20260125_schemas_name_get ...'
      end
      # verify the required parameter 'name' is set
      if @api_client.config.client_side_validation && name.nil?
        fail ArgumentError, "Missing the required parameter 'name' when calling SchemasApi.call_20260125_schemas_name_get"
      end
      # resource path
      local_var_path = '/2026-01-25/schemas/{name}'.sub('{' + 'name' + '}', CGI.escape(name.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/schema+json', 'application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SchemasApi.call_20260125_schemas_name_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SchemasApi#call_20260125_schemas_name_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
